import { test, expect } from '@playwright/test';
test('Директор: подрядчик → проблемный объект → причины → СК/ИД/СДО/закрытие', async ({page}, info) => {
  if(!process.env.MOCK_LOGIN_KEY) throw Error('Set mock test key for seeded test deployment');
  await page.goto('/');
  await page.getByLabel('Тестовый ключ').fill(process.env.MOCK_LOGIN_KEY);
  await page.getByRole('button',{name:'Войти',exact:true}).click();
  const portfolio = page.getByRole('region',{name:'Контроль по субподрядчикам'});
  await expect(portfolio.getByRole('heading',{name:'Подрядчики и объекты'})).toBeVisible();
  await portfolio.getByLabel('Светофор',{exact:true}).selectOption('RED');
  const group=portfolio.locator('details.RED').first();
  await expect(group).toBeVisible();
  if(!await group.getAttribute('open').then(x=>x!==null)) await group.locator('summary').click();
  const object=group.locator('.portfolio-object').first();
  await expect(object).toContainText('План объекта');
  await expect(object).toContainText('Факт объекта');
  await expect(object).toContainText('Отклонение');
  const objectName=await object.locator('h3').innerText();
  await portfolio.getByLabel('Объект, адрес или УКО').fill(objectName);
  await expect(portfolio.locator('.portfolio-object').first()).toContainText(objectName);
  await page.screenshot({path:info.outputPath('director-contractors.png'),fullPage:true});
  await portfolio.locator('.portfolio-object').first().getByRole('link',{name:objectName,exact:true}).click();
  const chain=page.getByRole('region',{name:'Сквозной производственный статус'});
  await expect(chain).toBeVisible();
  await expect(chain).toContainText('Отклонение');
  await expect(chain).toContainText('Стройконтроль');
  await expect(chain).toContainText('ИД / ПТО');
  await expect(chain).toContainText('СДО');
  await expect(chain).toContainText('Закрыто');
  await expect(chain.locator('.chain-work.RED').first()).toContainText('Выполненный объём ниже плана');
  await page.getByRole('tab',{name:'Строительный контроль',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Замечания',exact:true})).toBeVisible();
  await page.screenshot({path:info.outputPath('director-object.png'),fullPage:true});
});
