CREATE TABLE tenants(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),portal text UNIQUE NOT NULL,member_id text UNIQUE NOT NULL,name text NOT NULL,created_at timestamptz DEFAULT now(),updated_at timestamptz DEFAULT now());
CREATE TABLE users(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenants(id),bitrix_user_id text NOT NULL, name text NOT NULL, email text, department_id text, position text, role text NOT NULL, is_active boolean NOT NULL DEFAULT true, contractor_id uuid,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),version int NOT NULL DEFAULT 1,UNIQUE(tenant_id,id));
CREATE INDEX users_tenant_idx ON users(tenant_id);
CREATE TABLE contractors(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenants(id),name text NOT NULL, inn text, contact_data text, status text NOT NULL DEFAULT 'ACTIVE',created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),version int NOT NULL DEFAULT 1,UNIQUE(tenant_id,id));
CREATE INDEX contractors_tenant_idx ON contractors(tenant_id);
CREATE TABLE objects(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenants(id),external_code text NOT NULL, source text NOT NULL DEFAULT 'MANUAL', name text NOT NULL, address text NOT NULL, customer_name text, organization_name text, project_manager_id uuid NOT NULL, start_date date NOT NULL, planned_finish_date date NOT NULL, actual_finish_date date, contract_value numeric(20,2) NOT NULL CHECK(contract_value>=0), status text NOT NULL DEFAULT 'ACTIVE', health_status text NOT NULL DEFAULT 'GRAY',created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),version int NOT NULL DEFAULT 1,UNIQUE(tenant_id,id));
CREATE INDEX objects_tenant_idx ON objects(tenant_id);
CREATE TABLE object_contractors(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenants(id),object_id uuid NOT NULL, contractor_id uuid NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),version int NOT NULL DEFAULT 1,UNIQUE(tenant_id,id));
CREATE INDEX object_contractors_tenant_idx ON object_contractors(tenant_id);
CREATE TABLE work_categories(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenants(id),parent_id uuid, name text NOT NULL, code text NOT NULL, sort_order int NOT NULL DEFAULT 0, is_active boolean DEFAULT true,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),version int NOT NULL DEFAULT 1,UNIQUE(tenant_id,id));
CREATE INDEX work_categories_tenant_idx ON work_categories(tenant_id);
CREATE TABLE work_types(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenants(id),category_id uuid NOT NULL, name text NOT NULL, unit text NOT NULL, requires_inspection boolean DEFAULT true, requires_executive_docs boolean DEFAULT true, requires_materials boolean DEFAULT true, is_active boolean DEFAULT true,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),version int NOT NULL DEFAULT 1,UNIQUE(tenant_id,id));
CREATE INDEX work_types_tenant_idx ON work_types(tenant_id);
CREATE TABLE work_templates(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenants(id),work_type_id uuid NOT NULL, name text NOT NULL, default_quantity numeric(20,4),created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),version int NOT NULL DEFAULT 1,UNIQUE(tenant_id,id));
CREATE INDEX work_templates_tenant_idx ON work_templates(tenant_id);
CREATE TABLE works(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenants(id),object_id uuid NOT NULL, work_type_id uuid NOT NULL, contractor_id uuid NOT NULL, responsible_user_id uuid NOT NULL, name text NOT NULL, unit text NOT NULL, planned_quantity numeric(20,4) NOT NULL CHECK(planned_quantity>0), actual_quantity numeric(20,4) NOT NULL DEFAULT 0 CHECK(actual_quantity>=0), planned_start_date date NOT NULL, planned_finish_date date NOT NULL, actual_start_date date, actual_finish_date date, estimated_cost numeric(20,2) NOT NULL CHECK(estimated_cost>=0), status text NOT NULL DEFAULT 'PLANNED',created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),version int NOT NULL DEFAULT 1,UNIQUE(tenant_id,id));
CREATE INDEX works_tenant_idx ON works(tenant_id);
CREATE TABLE work_dependencies(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenants(id),predecessor_work_id uuid NOT NULL, successor_work_id uuid NOT NULL, dependency_type text NOT NULL DEFAULT 'FINISH_TO_START' CHECK(dependency_type='FINISH_TO_START'), requires_acceptance boolean DEFAULT true, requires_document boolean DEFAULT false, CHECK(predecessor_work_id<>successor_work_id),created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),version int NOT NULL DEFAULT 1,UNIQUE(tenant_id,id));
CREATE INDEX work_dependencies_tenant_idx ON work_dependencies(tenant_id);
CREATE TABLE work_progress(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenants(id),object_work_id uuid NOT NULL, quantity_delta numeric(20,4) NOT NULL, total_quantity numeric(20,4) NOT NULL, progress_percent numeric(7,4), reported_at timestamptz NOT NULL DEFAULT now(), reported_by uuid NOT NULL, comment text,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),version int NOT NULL DEFAULT 1,UNIQUE(tenant_id,id));
CREATE INDEX work_progress_tenant_idx ON work_progress(tenant_id);
CREATE TABLE inspections(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenants(id),object_id uuid NOT NULL, object_work_id uuid NOT NULL, requested_by uuid NOT NULL, requested_at timestamptz DEFAULT now(), inspector_id uuid, status text NOT NULL DEFAULT 'WAITING', inspection_date timestamptz, decision text, comment text, accepted_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),version int NOT NULL DEFAULT 1,UNIQUE(tenant_id,id));
CREATE INDEX inspections_tenant_idx ON inspections(tenant_id);
CREATE TABLE issues(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenants(id),inspection_id uuid NOT NULL, title text NOT NULL, description text, severity text NOT NULL CHECK(severity IN ('LOW','MEDIUM','HIGH','CRITICAL')), responsible_user_id uuid NOT NULL, due_date date NOT NULL, status text NOT NULL DEFAULT 'OPEN', resolved_at timestamptz, resolved_by uuid, verified_at timestamptz, verified_by uuid,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),version int NOT NULL DEFAULT 1,UNIQUE(tenant_id,id));
CREATE INDEX issues_tenant_idx ON issues(tenant_id);
CREATE TABLE attachments(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenants(id),file_provider text NOT NULL DEFAULT 'LOCAL', external_file_id text, file_name text NOT NULL, mime_type text NOT NULL, content bytea, uploaded_by uuid NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),version int NOT NULL DEFAULT 1,UNIQUE(tenant_id,id));
CREATE INDEX attachments_tenant_idx ON attachments(tenant_id);
CREATE TABLE inspection_photos(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenants(id),inspection_id uuid NOT NULL, issue_id uuid, attachment_id uuid NOT NULL, uploaded_by uuid NOT NULL, metadata jsonb,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),version int NOT NULL DEFAULT 1,UNIQUE(tenant_id,id));
CREATE INDEX inspection_photos_tenant_idx ON inspection_photos(tenant_id);
CREATE TABLE materials(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenants(id),name text NOT NULL, manufacturer text, brand text, type text,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),version int NOT NULL DEFAULT 1,UNIQUE(tenant_id,id));
CREATE INDEX materials_tenant_idx ON materials(tenant_id);
CREATE TABLE material_batches(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenants(id),material_id uuid NOT NULL, batch_number text NOT NULL, supplier text, delivery_date date, object_id uuid NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),version int NOT NULL DEFAULT 1,UNIQUE(tenant_id,id));
CREATE INDEX material_batches_tenant_idx ON material_batches(tenant_id);
CREATE TABLE material_documents(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenants(id),material_batch_id uuid NOT NULL, type text NOT NULL, number text NOT NULL, valid_from date, valid_until date, file_id uuid NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),version int NOT NULL DEFAULT 1,UNIQUE(tenant_id,id));
CREATE INDEX material_documents_tenant_idx ON material_documents(tenant_id);
CREATE TABLE work_materials(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenants(id),object_work_id uuid NOT NULL, material_batch_id uuid NOT NULL, quantity numeric(20,4) NOT NULL CHECK(quantity>0),created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),version int NOT NULL DEFAULT 1,UNIQUE(tenant_id,id));
CREATE INDEX work_materials_tenant_idx ON work_materials(tenant_id);
CREATE TABLE executive_documents(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenants(id),object_id uuid NOT NULL, object_work_id uuid NOT NULL, type text NOT NULL, number text NOT NULL, document_date date NOT NULL, status text NOT NULL DEFAULT 'DRAFT', file_id uuid, draft_content text, created_by uuid NOT NULL, approved_by uuid, approved_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),version int NOT NULL DEFAULT 1,UNIQUE(tenant_id,id));
CREATE INDEX executive_documents_tenant_idx ON executive_documents(tenant_id);
CREATE TABLE executive_packages(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenants(id),object_id uuid NOT NULL, object_work_id uuid NOT NULL, status text NOT NULL DEFAULT 'DRAFT', created_by uuid NOT NULL, completed_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),version int NOT NULL DEFAULT 1,UNIQUE(tenant_id,id));
CREATE INDEX executive_packages_tenant_idx ON executive_packages(tenant_id);
CREATE TABLE package_documents(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenants(id),package_id uuid NOT NULL, document_id uuid NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),version int NOT NULL DEFAULT 1,UNIQUE(tenant_id,id));
CREATE INDEX package_documents_tenant_idx ON package_documents(tenant_id);
CREATE TABLE pto_transfers(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenants(id),package_id uuid NOT NULL, transferred_by uuid NOT NULL, transferred_at timestamptz DEFAULT now(),created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),version int NOT NULL DEFAULT 1,UNIQUE(tenant_id,id));
CREATE INDEX pto_transfers_tenant_idx ON pto_transfers(tenant_id);
CREATE TABLE sdo_cases(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenants(id),object_id uuid NOT NULL, object_work_id uuid NOT NULL, executive_document_package_id uuid NOT NULL, status text NOT NULL DEFAULT 'TRANSFERRED', pto_transferred_at timestamptz DEFAULT now(), pto_transferred_by uuid NOT NULL, sdo_responsible_id uuid, estimated_value numeric(20,2), calculated_value numeric(20,2), accepted_closing_value numeric(20,2), calculated_at timestamptz, closed_at timestamptz, comment text,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),version int NOT NULL DEFAULT 1,UNIQUE(tenant_id,id));
CREATE INDEX sdo_cases_tenant_idx ON sdo_cases(tenant_id);
CREATE TABLE financial_closings(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenants(id),object_id uuid NOT NULL, sdo_case_id uuid NOT NULL, period text NOT NULL, amount numeric(20,2) NOT NULL CHECK(amount>0), closing_date date NOT NULL, created_by uuid NOT NULL, idempotency_key uuid NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),version int NOT NULL DEFAULT 1,UNIQUE(tenant_id,id));
CREATE INDEX financial_closings_tenant_idx ON financial_closings(tenant_id);
CREATE TABLE monthly_plans(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenants(id),object_id uuid NOT NULL, period text NOT NULL, planned_value numeric(20,2) NOT NULL CHECK(planned_value>=0), plan_type text NOT NULL CHECK(plan_type IN ('INTERMEDIATE','FINAL')),created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),version int NOT NULL DEFAULT 1,UNIQUE(tenant_id,id));
CREATE INDEX monthly_plans_tenant_idx ON monthly_plans(tenant_id);
CREATE TABLE audit_logs(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenants(id),user_id uuid NOT NULL, entity_type text NOT NULL, entity_id uuid NOT NULL, action text NOT NULL, old_value jsonb, new_value jsonb, ip text,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),version int NOT NULL DEFAULT 1,UNIQUE(tenant_id,id));
CREATE INDEX audit_logs_tenant_idx ON audit_logs(tenant_id);
CREATE TABLE domain_events(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenants(id),event_type text NOT NULL, entity_id uuid NOT NULL, payload jsonb NOT NULL, processed_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),version int NOT NULL DEFAULT 1,UNIQUE(tenant_id,id));
CREATE INDEX domain_events_tenant_idx ON domain_events(tenant_id);
CREATE TABLE notifications(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenants(id),user_id uuid NOT NULL, event_id uuid, title text NOT NULL, dedupe_key text NOT NULL, read_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),version int NOT NULL DEFAULT 1,UNIQUE(tenant_id,id));
CREATE INDEX notifications_tenant_idx ON notifications(tenant_id);
CREATE TABLE dictionary_items(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenants(id),kind text NOT NULL, code text NOT NULL, name text NOT NULL, is_active boolean DEFAULT true,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),version int NOT NULL DEFAULT 1,UNIQUE(tenant_id,id));
CREATE INDEX dictionary_items_tenant_idx ON dictionary_items(tenant_id);
CREATE TABLE risk_settings(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenants(id),yellow_variance numeric DEFAULT -5, red_variance numeric DEFAULT -15, stale_days int DEFAULT 7, pto_days int DEFAULT 5, sdo_days int DEFAULT 10, escalate_technical_days int DEFAULT 3, escalate_director_days int DEFAULT 7,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),version int NOT NULL DEFAULT 1,UNIQUE(tenant_id,id));
CREATE INDEX risk_settings_tenant_idx ON risk_settings(tenant_id);
CREATE TABLE bitrix_installations(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenants(id),portal text NOT NULL, member_id text NOT NULL, encrypted_access_token text NOT NULL, encrypted_refresh_token text NOT NULL, expires_at timestamptz NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),version int NOT NULL DEFAULT 1,UNIQUE(tenant_id,id));
CREATE INDEX bitrix_installations_tenant_idx ON bitrix_installations(tenant_id);
CREATE TABLE sessions(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenants(id),user_id uuid NOT NULL, token_hash text NOT NULL, expires_at timestamptz NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),version int NOT NULL DEFAULT 1,UNIQUE(tenant_id,id));
CREATE INDEX sessions_tenant_idx ON sessions(tenant_id);
CREATE TABLE import_reports(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenants(id),created_by uuid NOT NULL, file_name text NOT NULL, status text NOT NULL DEFAULT 'PREVIEW', report jsonb NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),version int NOT NULL DEFAULT 1,UNIQUE(tenant_id,id));
CREATE INDEX import_reports_tenant_idx ON import_reports(tenant_id);
ALTER TABLE users ADD FOREIGN KEY(tenant_id,contractor_id) REFERENCES contractors(tenant_id,id);
CREATE INDEX users_contractor_id_idx ON users(tenant_id,contractor_id);
CREATE INDEX users_created_idx ON users(tenant_id,created_at);
CREATE INDEX contractors_status_idx ON contractors(tenant_id,status);
CREATE INDEX contractors_created_idx ON contractors(tenant_id,created_at);
ALTER TABLE objects ADD FOREIGN KEY(tenant_id,project_manager_id) REFERENCES users(tenant_id,id);
CREATE INDEX objects_project_manager_id_idx ON objects(tenant_id,project_manager_id);
CREATE INDEX objects_status_idx ON objects(tenant_id,status);
CREATE INDEX objects_created_idx ON objects(tenant_id,created_at);
ALTER TABLE object_contractors ADD FOREIGN KEY(tenant_id,contractor_id) REFERENCES contractors(tenant_id,id);
CREATE INDEX object_contractors_contractor_id_idx ON object_contractors(tenant_id,contractor_id);
ALTER TABLE object_contractors ADD FOREIGN KEY(tenant_id,object_id) REFERENCES objects(tenant_id,id);
CREATE INDEX object_contractors_object_id_idx ON object_contractors(tenant_id,object_id);
CREATE INDEX object_contractors_created_idx ON object_contractors(tenant_id,created_at);
CREATE INDEX work_categories_created_idx ON work_categories(tenant_id,created_at);
ALTER TABLE work_types ADD FOREIGN KEY(tenant_id,category_id) REFERENCES work_categories(tenant_id,id);
CREATE INDEX work_types_category_id_idx ON work_types(tenant_id,category_id);
CREATE INDEX work_types_created_idx ON work_types(tenant_id,created_at);
ALTER TABLE work_templates ADD FOREIGN KEY(tenant_id,work_type_id) REFERENCES work_types(tenant_id,id);
CREATE INDEX work_templates_work_type_id_idx ON work_templates(tenant_id,work_type_id);
CREATE INDEX work_templates_created_idx ON work_templates(tenant_id,created_at);
ALTER TABLE works ADD FOREIGN KEY(tenant_id,contractor_id) REFERENCES contractors(tenant_id,id);
CREATE INDEX works_contractor_id_idx ON works(tenant_id,contractor_id);
ALTER TABLE works ADD FOREIGN KEY(tenant_id,object_id) REFERENCES objects(tenant_id,id);
CREATE INDEX works_object_id_idx ON works(tenant_id,object_id);
ALTER TABLE works ADD FOREIGN KEY(tenant_id,work_type_id) REFERENCES work_types(tenant_id,id);
CREATE INDEX works_work_type_id_idx ON works(tenant_id,work_type_id);
ALTER TABLE works ADD FOREIGN KEY(tenant_id,responsible_user_id) REFERENCES users(tenant_id,id);
CREATE INDEX works_responsible_user_id_idx ON works(tenant_id,responsible_user_id);
CREATE INDEX works_status_idx ON works(tenant_id,status);
CREATE INDEX works_created_idx ON works(tenant_id,created_at);
ALTER TABLE work_dependencies ADD FOREIGN KEY(tenant_id,predecessor_work_id) REFERENCES works(tenant_id,id);
CREATE INDEX work_dependencies_predecessor_work_id_idx ON work_dependencies(tenant_id,predecessor_work_id);
ALTER TABLE work_dependencies ADD FOREIGN KEY(tenant_id,successor_work_id) REFERENCES works(tenant_id,id);
CREATE INDEX work_dependencies_successor_work_id_idx ON work_dependencies(tenant_id,successor_work_id);
CREATE INDEX work_dependencies_created_idx ON work_dependencies(tenant_id,created_at);
ALTER TABLE work_progress ADD FOREIGN KEY(tenant_id,object_work_id) REFERENCES works(tenant_id,id);
CREATE INDEX work_progress_object_work_id_idx ON work_progress(tenant_id,object_work_id);
ALTER TABLE work_progress ADD FOREIGN KEY(tenant_id,reported_by) REFERENCES users(tenant_id,id);
CREATE INDEX work_progress_reported_by_idx ON work_progress(tenant_id,reported_by);
CREATE INDEX work_progress_created_idx ON work_progress(tenant_id,created_at);
ALTER TABLE inspections ADD FOREIGN KEY(tenant_id,object_id) REFERENCES objects(tenant_id,id);
CREATE INDEX inspections_object_id_idx ON inspections(tenant_id,object_id);
ALTER TABLE inspections ADD FOREIGN KEY(tenant_id,object_work_id) REFERENCES works(tenant_id,id);
CREATE INDEX inspections_object_work_id_idx ON inspections(tenant_id,object_work_id);
ALTER TABLE inspections ADD FOREIGN KEY(tenant_id,requested_by) REFERENCES users(tenant_id,id);
CREATE INDEX inspections_requested_by_idx ON inspections(tenant_id,requested_by);
ALTER TABLE inspections ADD FOREIGN KEY(tenant_id,inspector_id) REFERENCES users(tenant_id,id);
CREATE INDEX inspections_inspector_id_idx ON inspections(tenant_id,inspector_id);
CREATE INDEX inspections_status_idx ON inspections(tenant_id,status);
CREATE INDEX inspections_created_idx ON inspections(tenant_id,created_at);
ALTER TABLE issues ADD FOREIGN KEY(tenant_id,responsible_user_id) REFERENCES users(tenant_id,id);
CREATE INDEX issues_responsible_user_id_idx ON issues(tenant_id,responsible_user_id);
ALTER TABLE issues ADD FOREIGN KEY(tenant_id,inspection_id) REFERENCES inspections(tenant_id,id);
CREATE INDEX issues_inspection_id_idx ON issues(tenant_id,inspection_id);
ALTER TABLE issues ADD FOREIGN KEY(tenant_id,resolved_by) REFERENCES users(tenant_id,id);
CREATE INDEX issues_resolved_by_idx ON issues(tenant_id,resolved_by);
ALTER TABLE issues ADD FOREIGN KEY(tenant_id,verified_by) REFERENCES users(tenant_id,id);
CREATE INDEX issues_verified_by_idx ON issues(tenant_id,verified_by);
CREATE INDEX issues_status_idx ON issues(tenant_id,status);
CREATE INDEX issues_created_idx ON issues(tenant_id,created_at);
ALTER TABLE attachments ADD FOREIGN KEY(tenant_id,uploaded_by) REFERENCES users(tenant_id,id);
CREATE INDEX attachments_uploaded_by_idx ON attachments(tenant_id,uploaded_by);
CREATE INDEX attachments_created_idx ON attachments(tenant_id,created_at);
ALTER TABLE inspection_photos ADD FOREIGN KEY(tenant_id,inspection_id) REFERENCES inspections(tenant_id,id);
CREATE INDEX inspection_photos_inspection_id_idx ON inspection_photos(tenant_id,inspection_id);
ALTER TABLE inspection_photos ADD FOREIGN KEY(tenant_id,uploaded_by) REFERENCES users(tenant_id,id);
CREATE INDEX inspection_photos_uploaded_by_idx ON inspection_photos(tenant_id,uploaded_by);
ALTER TABLE inspection_photos ADD FOREIGN KEY(tenant_id,issue_id) REFERENCES issues(tenant_id,id);
CREATE INDEX inspection_photos_issue_id_idx ON inspection_photos(tenant_id,issue_id);
ALTER TABLE inspection_photos ADD FOREIGN KEY(tenant_id,attachment_id) REFERENCES attachments(tenant_id,id);
CREATE INDEX inspection_photos_attachment_id_idx ON inspection_photos(tenant_id,attachment_id);
CREATE INDEX inspection_photos_created_idx ON inspection_photos(tenant_id,created_at);
CREATE INDEX materials_created_idx ON materials(tenant_id,created_at);
ALTER TABLE material_batches ADD FOREIGN KEY(tenant_id,object_id) REFERENCES objects(tenant_id,id);
CREATE INDEX material_batches_object_id_idx ON material_batches(tenant_id,object_id);
ALTER TABLE material_batches ADD FOREIGN KEY(tenant_id,material_id) REFERENCES materials(tenant_id,id);
CREATE INDEX material_batches_material_id_idx ON material_batches(tenant_id,material_id);
CREATE INDEX material_batches_created_idx ON material_batches(tenant_id,created_at);
ALTER TABLE material_documents ADD FOREIGN KEY(tenant_id,material_batch_id) REFERENCES material_batches(tenant_id,id);
CREATE INDEX material_documents_material_batch_id_idx ON material_documents(tenant_id,material_batch_id);
ALTER TABLE material_documents ADD FOREIGN KEY(tenant_id,file_id) REFERENCES attachments(tenant_id,id);
CREATE INDEX material_documents_file_id_idx ON material_documents(tenant_id,file_id);
CREATE INDEX material_documents_created_idx ON material_documents(tenant_id,created_at);
ALTER TABLE work_materials ADD FOREIGN KEY(tenant_id,object_work_id) REFERENCES works(tenant_id,id);
CREATE INDEX work_materials_object_work_id_idx ON work_materials(tenant_id,object_work_id);
ALTER TABLE work_materials ADD FOREIGN KEY(tenant_id,material_batch_id) REFERENCES material_batches(tenant_id,id);
CREATE INDEX work_materials_material_batch_id_idx ON work_materials(tenant_id,material_batch_id);
CREATE INDEX work_materials_created_idx ON work_materials(tenant_id,created_at);
ALTER TABLE executive_documents ADD FOREIGN KEY(tenant_id,object_id) REFERENCES objects(tenant_id,id);
CREATE INDEX executive_documents_object_id_idx ON executive_documents(tenant_id,object_id);
ALTER TABLE executive_documents ADD FOREIGN KEY(tenant_id,object_work_id) REFERENCES works(tenant_id,id);
CREATE INDEX executive_documents_object_work_id_idx ON executive_documents(tenant_id,object_work_id);
ALTER TABLE executive_documents ADD FOREIGN KEY(tenant_id,file_id) REFERENCES attachments(tenant_id,id);
CREATE INDEX executive_documents_file_id_idx ON executive_documents(tenant_id,file_id);
ALTER TABLE executive_documents ADD FOREIGN KEY(tenant_id,created_by) REFERENCES users(tenant_id,id);
CREATE INDEX executive_documents_created_by_idx ON executive_documents(tenant_id,created_by);
ALTER TABLE executive_documents ADD FOREIGN KEY(tenant_id,approved_by) REFERENCES users(tenant_id,id);
CREATE INDEX executive_documents_approved_by_idx ON executive_documents(tenant_id,approved_by);
CREATE INDEX executive_documents_status_idx ON executive_documents(tenant_id,status);
CREATE INDEX executive_documents_created_idx ON executive_documents(tenant_id,created_at);
ALTER TABLE executive_packages ADD FOREIGN KEY(tenant_id,object_id) REFERENCES objects(tenant_id,id);
CREATE INDEX executive_packages_object_id_idx ON executive_packages(tenant_id,object_id);
ALTER TABLE executive_packages ADD FOREIGN KEY(tenant_id,object_work_id) REFERENCES works(tenant_id,id);
CREATE INDEX executive_packages_object_work_id_idx ON executive_packages(tenant_id,object_work_id);
ALTER TABLE executive_packages ADD FOREIGN KEY(tenant_id,created_by) REFERENCES users(tenant_id,id);
CREATE INDEX executive_packages_created_by_idx ON executive_packages(tenant_id,created_by);
CREATE INDEX executive_packages_status_idx ON executive_packages(tenant_id,status);
CREATE INDEX executive_packages_created_idx ON executive_packages(tenant_id,created_at);
ALTER TABLE package_documents ADD FOREIGN KEY(tenant_id,package_id) REFERENCES executive_packages(tenant_id,id);
CREATE INDEX package_documents_package_id_idx ON package_documents(tenant_id,package_id);
ALTER TABLE package_documents ADD FOREIGN KEY(tenant_id,document_id) REFERENCES executive_documents(tenant_id,id);
CREATE INDEX package_documents_document_id_idx ON package_documents(tenant_id,document_id);
CREATE INDEX package_documents_created_idx ON package_documents(tenant_id,created_at);
ALTER TABLE pto_transfers ADD FOREIGN KEY(tenant_id,package_id) REFERENCES executive_packages(tenant_id,id);
CREATE INDEX pto_transfers_package_id_idx ON pto_transfers(tenant_id,package_id);
ALTER TABLE pto_transfers ADD FOREIGN KEY(tenant_id,transferred_by) REFERENCES users(tenant_id,id);
CREATE INDEX pto_transfers_transferred_by_idx ON pto_transfers(tenant_id,transferred_by);
CREATE INDEX pto_transfers_created_idx ON pto_transfers(tenant_id,created_at);
ALTER TABLE sdo_cases ADD FOREIGN KEY(tenant_id,object_id) REFERENCES objects(tenant_id,id);
CREATE INDEX sdo_cases_object_id_idx ON sdo_cases(tenant_id,object_id);
ALTER TABLE sdo_cases ADD FOREIGN KEY(tenant_id,object_work_id) REFERENCES works(tenant_id,id);
CREATE INDEX sdo_cases_object_work_id_idx ON sdo_cases(tenant_id,object_work_id);
ALTER TABLE sdo_cases ADD FOREIGN KEY(tenant_id,executive_document_package_id) REFERENCES executive_packages(tenant_id,id);
CREATE INDEX sdo_cases_executive_document_package_id_idx ON sdo_cases(tenant_id,executive_document_package_id);
ALTER TABLE sdo_cases ADD FOREIGN KEY(tenant_id,pto_transferred_by) REFERENCES users(tenant_id,id);
CREATE INDEX sdo_cases_pto_transferred_by_idx ON sdo_cases(tenant_id,pto_transferred_by);
ALTER TABLE sdo_cases ADD FOREIGN KEY(tenant_id,sdo_responsible_id) REFERENCES users(tenant_id,id);
CREATE INDEX sdo_cases_sdo_responsible_id_idx ON sdo_cases(tenant_id,sdo_responsible_id);
CREATE INDEX sdo_cases_status_idx ON sdo_cases(tenant_id,status);
CREATE INDEX sdo_cases_created_idx ON sdo_cases(tenant_id,created_at);
ALTER TABLE financial_closings ADD FOREIGN KEY(tenant_id,object_id) REFERENCES objects(tenant_id,id);
CREATE INDEX financial_closings_object_id_idx ON financial_closings(tenant_id,object_id);
ALTER TABLE financial_closings ADD FOREIGN KEY(tenant_id,created_by) REFERENCES users(tenant_id,id);
CREATE INDEX financial_closings_created_by_idx ON financial_closings(tenant_id,created_by);
ALTER TABLE financial_closings ADD FOREIGN KEY(tenant_id,sdo_case_id) REFERENCES sdo_cases(tenant_id,id);
CREATE INDEX financial_closings_sdo_case_id_idx ON financial_closings(tenant_id,sdo_case_id);
CREATE INDEX financial_closings_created_idx ON financial_closings(tenant_id,created_at);
ALTER TABLE monthly_plans ADD FOREIGN KEY(tenant_id,object_id) REFERENCES objects(tenant_id,id);
CREATE INDEX monthly_plans_object_id_idx ON monthly_plans(tenant_id,object_id);
CREATE INDEX monthly_plans_created_idx ON monthly_plans(tenant_id,created_at);
ALTER TABLE audit_logs ADD FOREIGN KEY(tenant_id,user_id) REFERENCES users(tenant_id,id);
CREATE INDEX audit_logs_user_id_idx ON audit_logs(tenant_id,user_id);
CREATE INDEX audit_logs_created_idx ON audit_logs(tenant_id,created_at);
CREATE INDEX domain_events_created_idx ON domain_events(tenant_id,created_at);
ALTER TABLE notifications ADD FOREIGN KEY(tenant_id,user_id) REFERENCES users(tenant_id,id);
CREATE INDEX notifications_user_id_idx ON notifications(tenant_id,user_id);
ALTER TABLE notifications ADD FOREIGN KEY(tenant_id,event_id) REFERENCES domain_events(tenant_id,id);
CREATE INDEX notifications_event_id_idx ON notifications(tenant_id,event_id);
CREATE INDEX notifications_created_idx ON notifications(tenant_id,created_at);
CREATE INDEX dictionary_items_created_idx ON dictionary_items(tenant_id,created_at);
CREATE INDEX risk_settings_created_idx ON risk_settings(tenant_id,created_at);
CREATE INDEX bitrix_installations_created_idx ON bitrix_installations(tenant_id,created_at);
ALTER TABLE sessions ADD FOREIGN KEY(tenant_id,user_id) REFERENCES users(tenant_id,id);
CREATE INDEX sessions_user_id_idx ON sessions(tenant_id,user_id);
CREATE INDEX sessions_created_idx ON sessions(tenant_id,created_at);
ALTER TABLE import_reports ADD FOREIGN KEY(tenant_id,created_by) REFERENCES users(tenant_id,id);
CREATE INDEX import_reports_created_by_idx ON import_reports(tenant_id,created_by);
CREATE INDEX import_reports_status_idx ON import_reports(tenant_id,status);
CREATE INDEX import_reports_created_idx ON import_reports(tenant_id,created_at);
CREATE UNIQUE INDEX users_unique ON users(tenant_id,bitrix_user_id);
CREATE UNIQUE INDEX objects_unique ON objects(tenant_id,source,external_code);
CREATE UNIQUE INDEX object_contractors_unique ON object_contractors(tenant_id,object_id,contractor_id);
CREATE UNIQUE INDEX work_dependencies_unique ON work_dependencies(tenant_id,predecessor_work_id,successor_work_id);
CREATE UNIQUE INDEX package_documents_unique ON package_documents(tenant_id,package_id,document_id);
CREATE UNIQUE INDEX pto_transfers_unique ON pto_transfers(tenant_id,package_id);
CREATE UNIQUE INDEX sdo_cases_unique ON sdo_cases(tenant_id,executive_document_package_id);
CREATE UNIQUE INDEX financial_closings_unique ON financial_closings(tenant_id,idempotency_key);
CREATE UNIQUE INDEX notifications_unique ON notifications(tenant_id,dedupe_key);
CREATE UNIQUE INDEX risk_settings_unique ON risk_settings(tenant_id);
CREATE UNIQUE INDEX bitrix_installations_unique ON bitrix_installations(tenant_id,member_id);
CREATE UNIQUE INDEX sessions_unique ON sessions(tenant_id,token_hash);
CREATE UNIQUE INDEX monthly_plans_unique ON monthly_plans(tenant_id,object_id,period,plan_type);
ALTER TABLE work_categories ADD FOREIGN KEY(tenant_id,parent_id) REFERENCES work_categories(tenant_id,id);
ALTER TABLE objects ADD CHECK(planned_finish_date>=start_date);
ALTER TABLE works ADD CHECK(planned_finish_date>=planned_start_date);
CREATE INDEX works_deadline ON works(tenant_id,planned_finish_date);
CREATE UNIQUE INDEX inspection_active ON inspections(tenant_id,object_work_id) WHERE status IN ('WAITING','IN_REVIEW','ISSUES_FOUND','REINSPECTION');
CREATE FUNCTION immutable_history() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'Append-only history'; END $$;
CREATE TRIGGER audit_immutable BEFORE UPDATE OR DELETE ON audit_logs FOR EACH ROW EXECUTE FUNCTION immutable_history();
CREATE TRIGGER progress_immutable BEFORE UPDATE OR DELETE ON work_progress FOR EACH ROW EXECUTE FUNCTION immutable_history();
CREATE TRIGGER closing_immutable BEFORE UPDATE OR DELETE ON financial_closings FOR EACH ROW EXECUTE FUNCTION immutable_history();
