import {test} from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import Decimal from 'decimal.js';

test('Acceptance: populated tenants, negative RBAC, concurrent writes, financial rollback and SQL invariants',async(t)=>{
 if(!process.env.E2E_DATABASE_URL) delete process.env.DATABASE_URL;
 process.env.AUTH_MODE='mock';process.env.MOCK_LOGIN_KEY='acceptance-only';process.env.DB_MODE=process.env.E2E_DATABASE_URL?'postgres':'pglite';process.env.PGLITE_DIR='memory://';
 if(process.env.E2E_DATABASE_URL){assert.ok(new URL(process.env.E2E_DATABASE_URL).pathname.endsWith('_test'));process.env.DATABASE_URL=process.env.E2E_DATABASE_URL;}
 const {pool,one,insert,transaction}=await import('../apps/backend/src/db');const {migrate}=await import('../scripts/migrate');const {createApp}=await import('../apps/backend/src/main');const {session}=await import('../apps/backend/src/security');await migrate();await migrate();const app=await createApp();await app.listen(0,'127.0.0.1');const base=await app.getUrl();
 async function request(token:string,path:string,data?:any){const r=await fetch(base+'/'+path,{method:data===undefined?'GET':'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:data===undefined?undefined:JSON.stringify(data)});return {status:r.status,data:await r.json() as any};}
 async function fixture(label:string){return transaction(async c=>{const tenant=await one(c,'INSERT INTO tenants(portal,member_id,name) VALUES($1,$2,$3) RETURNING *',[label+randomUUID()+'.local',randomUUID(),label]);const tid=tenant.id;const users:any={};for(const role of ['ADMIN','PROJECT_MANAGER','PTO','SDO','CONSTRUCTION_CONTROL','GENERAL_DIRECTOR','CONTRACTOR_VIEWER'])users[role]=await insert(c,'users',tid,{bitrixUserId:role,name:label+' '+role,role});const contractor=await insert(c,'contractors',tid,{name:label+' contractor'});const object=await insert(c,'objects',tid,{externalCode:'SAME-CODE',name:label+' object',address:label+' address',organizationName:label,projectManagerId:users.PROJECT_MANAGER.id,startDate:'2026-01-01',plannedFinishDate:'2026-12-31',contractValue:'100.10'});await insert(c,'object_contractors',tid,{objectId:object.id,contractorId:contractor.id});await c.query('UPDATE users SET contractor_id=$2 WHERE id=$1',[users.CONTRACTOR_VIEWER.id,contractor.id]);const category=await insert(c,'work_categories',tid,{name:'Конструктив',code:'SAME'});const type=await insert(c,'work_types',tid,{categoryId:category.id,name:'Армирование',unit:'т'});const work=await insert(c,'works',tid,{objectId:object.id,workTypeId:type.id,contractorId:contractor.id,responsibleUserId:users.PROJECT_MANAGER.id,name:'Армирование',unit:'т',plannedQuantity:20,actualQuantity:20,plannedStartDate:'2026-01-01',plannedFinishDate:'2026-12-31',estimatedCost:'100.10',status:'COMPLETED'});const inspection=await insert(c,'inspections',tid,{objectId:object.id,objectWorkId:work.id,requestedBy:users.PROJECT_MANAGER.id});const pack=await insert(c,'executive_packages',tid,{objectId:object.id,objectWorkId:work.id,createdBy:users.PTO.id});const sdo=await insert(c,'sdo_cases',tid,{objectId:object.id,objectWorkId:work.id,executiveDocumentPackageId:pack.id,ptoTransferredBy:users.PTO.id,status:'CALCULATED',calculatedValue:'100.10',acceptedClosingValue:'100.10'});await insert(c,'risk_settings',tid,{});const tokens:any={};for(const [role,u] of Object.entries(users))tokens[role]=(await session(u,c)).token;return {tid,users,tokens,contractor,object,work,inspection,pack,sdo};});}
 const A=await fixture('A'),B=await fixture('B');const today=new Date().toISOString().slice(0,10);const closing=(f:any,amount:string)=>({sdoCaseId:f.sdo.id,amount,period:today.slice(0,7),closingDate:today,version:f.sdo.version,idempotencyKey:randomUUID()});
 try{
 await t.test('RBAC denied by API for PM, PTO, SDO and contractor',async()=>{for(const role of ['PROJECT_MANAGER','SDO'])assert.equal((await request(A.tokens[role],`inspections/${A.inspection.id}/accept`,{version:1,comment:'forbidden'})).status,403);assert.equal((await request(A.tokens.PTO,'financial-closings',closing(A,'1.00'))).status,403);assert.equal((await request(A.tokens.CONTRACTOR_VIEWER,'objects',{externalCode:'new',name:'new',address:'new',organizationName:'new',projectManagerId:A.users.PROJECT_MANAGER.id,startDate:today,plannedFinishDate:today,contractValue:'1',contractorIds:[A.contractor.id]})).status,403);});
 await t.test('Negative/NaN/invalid/excess closing does not mutate',async()=>{for(const amount of ['-1','NaN','Infinity','1e3','1.001','100.11'])assert.equal((await request(A.tokens.SDO,'financial-closings',closing(A,amount))).status,400);assert.equal((await one(pool,'SELECT count(*) AS n FROM financial_closings WHERE tenant_id=$1',[A.tid])).n,process.env.DB_MODE==='postgres'?'0':0);});
 await t.test('Exact Decimal, concurrent idempotent retry, dashboard/object reconciliation',async()=>{const d=closing(A,'0.10');const results=await Promise.all([request(A.tokens.SDO,'financial-closings',d),request(A.tokens.SDO,'financial-closings',d)]);assert.deepEqual(results.map(x=>x.status),[201,201]);assert.equal(results[0].data.id,results[1].data.id);const snap=(await request(A.tokens.ADMIN,'snapshot')).data;assert.equal(snap.objects[0].closed,'0.10');assert.equal(snap.dashboard.closedThisMonth,'0.10');assert.equal(snap.objects[0].potential,'100.00');assert.equal(snap.dashboard.potentialClosing,'100.00');const detail=(await request(A.tokens.ADMIN,'objects/'+A.object.id)).data;assert.equal(detail.object.closed,snap.objects[0].closed);assert.equal(new Decimal(snap.dashboard.potentialClosing).add(snap.dashboard.closedThisMonth).toFixed(2),'100.10');});
 await t.test('Two populated tenants: objects, works, contractors, finances, dashboard, audit',async()=>{assert.equal((await request(B.tokens.SDO,'financial-closings',closing(B,'40.00'))).status,201);for(const [self,other,closed] of [[A,B,'0.10'],[B,A,'40.00']] as any){const snapshot=(await request(self.tokens.ADMIN,'snapshot')).data;assert.deepEqual(snapshot.objects.map(x=>x.id),[self.object.id]);assert.deepEqual(snapshot.works.map(x=>x.id),[self.work.id]);assert.deepEqual(snapshot.contractors.map(x=>x.id),[self.contractor.id]);assert.ok(snapshot.closings.every(x=>x.tenantId===self.tid));assert.equal(snapshot.dashboard.closedThisMonth,closed);assert.equal(snapshot.dashboard.activeObjects,1);const logs=(await request(self.tokens.ADMIN,'audit')).data;assert.ok(logs.length>0&&logs.every(x=>x.tenantId===self.tid));for(const path of ['objects/'+other.object.id,'works/'+other.work.id,'works/'+other.work.id+'/progress'])assert.equal((await request(self.tokens.ADMIN,path)).status,404);assert.equal((await request(self.tokens.SDO,'financial-closings',closing(other,'1'))).status,404);}});
 await t.test('Two sessions race on version N: exactly one update and one conflict',async()=>{const work=await insert(pool,'works',A.tid,{objectId:A.object.id,workTypeId:A.work.workTypeId,contractorId:A.contractor.id,responsibleUserId:A.users.PROJECT_MANAGER.id,name:'Concurrency',unit:'т',plannedQuantity:20,plannedStartDate:today,plannedFinishDate:today,estimatedCost:'0'});const read=(await request(A.tokens.PROJECT_MANAGER,'works/'+work.id)).data;const result=await Promise.all([request(A.tokens.PROJECT_MANAGER,`works/${work.id}/progress`,{version:read.version,totalQuantity:10,comment:'A'}),request(A.tokens.ADMIN,`works/${work.id}/progress`,{version:read.version,totalQuantity:12,comment:'B'})]);assert.deepEqual(result.map(x=>x.status).sort(),[201,409]);assert.match(result.find(x=>x.status===409)!.data.message,/Обновите/);const progress=(await request(A.tokens.ADMIN,`works/${work.id}/progress`)).data;assert.equal(progress.length,1);});
 await t.test('SQL rollback after insert and restrict/UUID/JSONB/index constraints',async()=>{const auditBefore=await one(pool,'SELECT count(*) AS n FROM audit_logs WHERE tenant_id=$1',[A.tid]);await assert.rejects(()=>transaction(async c=>{await insert(c,'financial_closings',A.tid,{objectId:A.object.id,sdoCaseId:A.sdo.id,period:today.slice(0,7),amount:'0.01',closingDate:today,createdBy:A.users.SDO.id,idempotencyKey:randomUUID()});await insert(c,'audit_logs',A.tid,{userId:A.users.SDO.id,entityType:'Rollback',entityId:A.object.id,action:'TEST',newValue:JSON.stringify({value:'rollback'})});throw Error('Injected transaction failure')}),/Injected/);assert.equal((await one(pool,'SELECT sum(amount)::text AS amount FROM financial_closings WHERE tenant_id=$1',[A.tid])).amount,'0.10');assert.deepEqual(await one(pool,'SELECT count(*) AS n FROM audit_logs WHERE tenant_id=$1',[A.tid]),auditBefore);await assert.rejects(()=>pool.query('DELETE FROM objects WHERE id=$1',[A.object.id]),/foreign key/);await assert.rejects(()=>insert(pool,'object_contractors',A.tid,{objectId:A.object.id,contractorId:B.contractor.id}),/foreign key/);await assert.rejects(()=>pool.query('SELECT $1::uuid',['not-uuid']),/uuid/);const row=await one(pool,"SELECT '{\"a\":1}'::jsonb->>'a' AS value, '2026-09-15'::date AS date, '2026-09-15 03:00:00+03'::timestamptz AS timestamp");assert.equal(row.value,'1');assert.equal(String(row.date).slice(0,10),'2026-09-15');assert.equal(new Date(row.timestamp).toISOString(),'2026-09-15T00:00:00.000Z');const indexes=await pool.query("SELECT indexname FROM pg_indexes WHERE schemaname='public' AND indexname IN ('sdo_one_per_work','financial_closings_unique','inspection_active')");assert.equal(indexes.rows.length,3);});
 await t.test('Logout revokes session',async()=>{assert.equal((await request(A.tokens.PROJECT_MANAGER,'auth/logout',{})).status,201);assert.equal((await request(A.tokens.PROJECT_MANAGER,'me')).status,401);});
 }finally{await app.close();await pool.end();}
});
