import {test} from 'node:test';import assert from 'node:assert/strict';
test('Bitrix provider contracts and installation/refresh with simulated transport only',async(t)=>{
 delete process.env.DATABASE_URL; process.env.DB_MODE='pglite';process.env.PGLITE_DIR='memory://';process.env.AUTH_MODE='bitrix';process.env.BITRIX_PORTAL='acceptance.bitrix24.com';delete process.env.BITRIX_MEMBER_ID;process.env.BITRIX_ADMIN_USER_ID='7';process.env.BITRIX_CLIENT_ID='local.test';process.env.BITRIX_CLIENT_SECRET='test-client-secret';process.env.TOKEN_ENCRYPTION_KEY='2'.repeat(64);
 const {pool,one}=await import('../apps/backend/src/db');const {migrate}=await import('../scripts/migrate');await migrate();const {RealBitrixAdapter,MockBitrixAdapter,installBitrix,bitrixLogin,onAppInstallWebhook,verifyApplicationToken}=await import('../apps/backend/src/bitrix');const {decrypt}=await import('../apps/backend/src/security');const {createApp}=await import('../apps/backend/src/main');const originalFetch=globalThis.fetch;const calls:any[]=[];const expiredTokens=new Set<string>();let refreshes=0;
 globalThis.fetch=async(input:any,init:any)=>{const url=String(input);if(url.startsWith('http://127.0.0.1:'))return originalFetch(input,init);calls.push({url,body:init.body});if(url==='https://oauth.bitrix.info/oauth/token/'){refreshes++;return new Response(JSON.stringify({access_token:'access-'+refreshes,refresh_token:'refresh-'+refreshes,expires_in:3600,member_id:'acceptance-member'}));}const b=JSON.parse(init.body);if(expiredTokens.has(b.auth))return new Response(JSON.stringify({error:'expired_token'}),{status:401});return new Response(JSON.stringify({result:url.includes('user.current')?{ID:'7',NAME:'Test Admin'}:true}));};
 try{
 await t.test('Mock providers return explicit mock results',async()=>{const m=new MockBitrixAdapter();assert.equal((await m.currentUser('9')).ID,'9');assert.ok((await m.notify('','9','message')).mock);assert.ok((await m.createTask('','9','task')).mock);assert.ok((await m.upload('','','file')).mock);assert.equal((await m.departments()).length,1);});
 await t.test('Real adapter method names and payloads use simulated transport',async()=>{const r=new RealBitrixAdapter();await r.currentUser('test');await r.departments('test');await r.notify('test','9','text');await r.createTask('test','9','task');await r.upload('test','3','file.pdf','YWJj');assert.ok(calls.some(x=>x.url.endsWith('/im.notify.system.add.json')&&JSON.parse(x.body).USER_ID==='9'));assert.ok(calls.some(x=>x.url.endsWith('/tasks.task.add.json')&&JSON.parse(x.body).fields.RESPONSIBLE_ID===9));assert.ok(calls.some(x=>x.url.endsWith('/disk.folder.uploadfile.json')&&JSON.parse(x.body).fileContent[0]==='file.pdf'));assert.throws(()=>new RealBitrixAdapter('127.0.0.1'));});
 await t.test('Wizard install binds member_id without env pin and stores application_token encrypted',async()=>{const r=await installBitrix({DOMAIN:process.env.BITRIX_PORTAL,REFRESH_ID:'initial',member_id:'acceptance-member',APPLICATION_TOKEN:'wizard-app-token'});assert.equal(r.user.role,'ADMIN');const tenant=await one(pool,'SELECT * FROM tenants WHERE portal=$1',[process.env.BITRIX_PORTAL]);assert.equal(tenant.memberId,'acceptance-member');const stored=await one(pool,'SELECT * FROM bitrix_installations WHERE tenant_id=$1',[tenant.id]);assert.equal(decrypt(stored.encryptedAccessToken),'access-1');assert.equal(decrypt(stored.encryptedApplicationToken),'wizard-app-token');assert.notEqual(stored.encryptedAccessToken,'access-1');assert.notEqual(stored.encryptedApplicationToken,'wizard-app-token');});
 await t.test('Launch requires exact member_id and application_token before user.current',async()=>{const login=await bitrixLogin({DOMAIN:process.env.BITRIX_PORTAL,AUTH_ID:'access-1',member_id:'acceptance-member',APPLICATION_TOKEN:'wizard-app-token'});assert.ok(login.token&&!JSON.stringify(login).includes('access-1'));for(const bad of [{member_id:'acceptance-member',APPLICATION_TOKEN:'wrong-token'},{member_id:'wrong-member',APPLICATION_TOKEN:'wizard-app-token'}]){const n=calls.length;await assert.rejects(()=>bitrixLogin({DOMAIN:process.env.BITRIX_PORTAL,AUTH_ID:'untrusted-access',...bad}),/Bitrix/);assert.equal(calls.length,n);}await assert.rejects(()=>bitrixLogin({DOMAIN:'other.bitrix24.com',AUTH_ID:'access-1',member_id:'acceptance-member',APPLICATION_TOKEN:'wizard-app-token'}));});
 await t.test('Reinstall rejects token replacement, but legacy NULL can be filled after full verification',async()=>{let n=calls.length;await assert.rejects(()=>installBitrix({DOMAIN:process.env.BITRIX_PORTAL,REFRESH_ID:'bad-reinstall',member_id:'acceptance-member',APPLICATION_TOKEN:'different-app-token'}),/application token/i);assert.equal(calls.length,n);const tenant=await one(pool,'SELECT * FROM tenants WHERE portal=$1',[process.env.BITRIX_PORTAL]);await pool.query('UPDATE bitrix_installations SET encrypted_application_token=NULL WHERE tenant_id=$1',[tenant.id]);await installBitrix({DOMAIN:process.env.BITRIX_PORTAL,REFRESH_ID:'legacy-fill',member_id:'acceptance-member',APPLICATION_TOKEN:'wizard-app-token'});const stored=await one(pool,'SELECT * FROM bitrix_installations WHERE tenant_id=$1',[tenant.id]);assert.equal(decrypt(stored.encryptedApplicationToken),'wizard-app-token');assert.equal(decrypt(stored.encryptedAccessToken),'access-2');});
 await t.test('BITRIX_MEMBER_ID remains an optional operator pin',async()=>{process.env.BITRIX_MEMBER_ID='different-member';const n=calls.length;await assert.rejects(()=>installBitrix({DOMAIN:process.env.BITRIX_PORTAL,REFRESH_ID:'pinned',member_id:'acceptance-member',APPLICATION_TOKEN:'wizard-app-token'}),/member/i);assert.equal(calls.length,n);process.env.BITRIX_MEMBER_ID='acceptance-member';});
 await t.test('Expired token rotates once, persists pair, rejects mismatched portal',async()=>{expiredTokens.add('access-2');const tenant=await one(pool,'SELECT * FROM tenants WHERE portal=$1',[process.env.BITRIX_PORTAL]);const r=new RealBitrixAdapter();await r.installedCall(tenant.id,'user.current');const stored=await one(pool,'SELECT * FROM bitrix_installations WHERE tenant_id=$1',[tenant.id]);assert.equal(decrypt(stored.encryptedRefreshToken),'refresh-3');await r.installedCall(tenant.id,'user.current');assert.equal(refreshes,3);const n=calls.length;await assert.rejects(()=>new RealBitrixAdapter('other.bitrix24.com').installedCall(tenant.id,'user.current'));assert.equal(calls.length,n);});
 const webhookPayload={auth:{domain:'webhook.bitrix24.com',member_id:'webhook-member-id',access_token:'wh-access-token',refresh_token:'wh-refresh-token',application_token:'wh-application-token',expires_in:3600}};
 await t.test('ONAPPINSTALL webhook fail-closed by default: no env flag, nothing written',async()=>{delete process.env.BITRIX_INSTALL_WEBHOOK_ENABLED;const res=await onAppInstallWebhook(webhookPayload);assert.equal(res.result,false);const tenant=await one(pool,'SELECT * FROM tenants WHERE member_id=$1',['webhook-member-id']);assert.equal(tenant,undefined);});
 await t.test('ONAPPINSTALL webhook enabled: valid payload stores encrypted application_token',async()=>{process.env.BITRIX_INSTALL_WEBHOOK_ENABLED='true';const res=await onAppInstallWebhook(webhookPayload);assert.equal(res.result,true);const tenant=await one(pool,'SELECT * FROM tenants WHERE member_id=$1',['webhook-member-id']);assert.equal(tenant.portal,'webhook.bitrix24.com');const stored=await one(pool,'SELECT * FROM bitrix_installations WHERE tenant_id=$1',[tenant.id]);assert.equal(decrypt(stored.encryptedApplicationToken),'wh-application-token');assert.notEqual(stored.encryptedApplicationToken,'wh-application-token');});
 await t.test('ONAPPINSTALL webhook rejects malformed/missing fields even when enabled',async()=>{process.env.BITRIX_INSTALL_WEBHOOK_ENABLED='true';assert.equal((await onAppInstallWebhook({auth:{...webhookPayload.auth,application_token:undefined}})).result,false);assert.equal((await onAppInstallWebhook({auth:{...webhookPayload.auth,domain:'not a hostname'}})).result,false);assert.equal((await onAppInstallWebhook({auth:{...webhookPayload.auth,access_token:'short'}})).result,false);assert.equal((await onAppInstallWebhook({auth:{...webhookPayload.auth,expires_in:-1}})).result,false);});
 await t.test('verifyApplicationToken accepts only the exact stored token for that member_id',async()=>{assert.equal(await verifyApplicationToken('webhook-member-id','wh-application-token'),true);assert.equal(await verifyApplicationToken('webhook-member-id','wrong-token'),false);assert.equal(await verifyApplicationToken('unknown-member-id','wh-application-token'),false);assert.equal(await verifyApplicationToken(undefined,'wh-application-token'),false);});
 await t.test('HTTP wizard handlers take DOMAIN from query string and auth fields from form body',async()=>{process.env.BITRIX_INSTALL_WEBHOOK_ENABLED='false';const app=await createApp();await app.listen(0,'127.0.0.1');const base=await app.getUrl();try{const installBody=new URLSearchParams({REFRESH_ID:'http-reinstall',member_id:'acceptance-member',APPLICATION_TOKEN:'wizard-app-token'});const install=await originalFetch(base+'/auth/bitrix/install?DOMAIN=acceptance.bitrix24.com',{method:'POST',headers:{Origin:'https://acceptance.bitrix24.com','Content-Type':'application/x-www-form-urlencoded'},body:installBody});assert.equal(install.status,201);assert.match(await install.text(),/BX24\.installFinish/);const launchBody=new URLSearchParams({AUTH_ID:'http-access',member_id:'acceptance-member',APPLICATION_TOKEN:'wizard-app-token'});const launch=await originalFetch(base+'/auth/bitrix/launch?DOMAIN=acceptance.bitrix24.com',{method:'POST',headers:{Origin:'https://acceptance.bitrix24.com','Content-Type':'application/x-www-form-urlencoded'},body:launchBody});assert.equal(launch.status,201);assert.match(await launch.text(),/sessionStorage\.setItem/);}finally{await app.close();}});
 }finally{globalThis.fetch=originalFetch;delete process.env.BITRIX_MEMBER_ID;await pool.end();}
});
