import {test} from 'node:test';import assert from 'node:assert/strict';
test('Bitrix provider contracts and installation/refresh with simulated transport only',async(t)=>{
 delete process.env.DATABASE_URL; process.env.DB_MODE='pglite';process.env.PGLITE_DIR='memory://';process.env.AUTH_MODE='bitrix';process.env.BITRIX_PORTAL='acceptance.bitrix24.com';process.env.BITRIX_MEMBER_ID='acceptance-member';process.env.BITRIX_ADMIN_USER_ID='7';process.env.BITRIX_CLIENT_ID='local.test';process.env.BITRIX_CLIENT_SECRET='test-client-secret';process.env.TOKEN_ENCRYPTION_KEY='2'.repeat(64);
 const {pool,one}=await import('../apps/backend/src/db');const {migrate}=await import('../scripts/migrate');await migrate();const {RealBitrixAdapter,MockBitrixAdapter,installBitrix,bitrixLogin,onAppInstallWebhook,verifyApplicationToken}=await import('../apps/backend/src/bitrix');const {decrypt}=await import('../apps/backend/src/security');const originalFetch=globalThis.fetch;const calls:any[]=[];let expired=false,refreshes=0;
 globalThis.fetch=async(input:any,init:any)=>{const url=String(input);calls.push({url,body:init.body});if(url==='https://oauth.bitrix.info/oauth/token/'){refreshes++;return new Response(JSON.stringify({access_token:'access-'+refreshes,refresh_token:'refresh-'+refreshes,expires_in:3600,member_id:'acceptance-member'}));}const b=JSON.parse(init.body);if(expired&&b.auth==='access-1')return new Response(JSON.stringify({error:'expired_token'}),{status:401});return new Response(JSON.stringify({result:url.includes('user.current')?{ID:'7',NAME:'Test Admin'}:true}));};
 try{
 await t.test('Mock providers return explicit mock results',async()=>{const m=new MockBitrixAdapter();assert.equal((await m.currentUser('9')).ID,'9');assert.ok((await m.notify('','9','message')).mock);assert.ok((await m.createTask('','9','task')).mock);assert.ok((await m.upload('','','file')).mock);assert.equal((await m.departments()).length,1);});
 await t.test('Real adapter method names and payloads use simulated transport',async()=>{const r=new RealBitrixAdapter();await r.currentUser('test');await r.departments('test');await r.notify('test','9','text');await r.createTask('test','9','task');await r.upload('test','3','file.pdf','YWJj');assert.ok(calls.some(x=>x.url.endsWith('/im.notify.system.add.json')&&JSON.parse(x.body).USER_ID==='9'));assert.ok(calls.some(x=>x.url.endsWith('/tasks.task.add.json')&&JSON.parse(x.body).fields.RESPONSIBLE_ID===9));assert.ok(calls.some(x=>x.url.endsWith('/disk.folder.uploadfile.json')&&JSON.parse(x.body).fileContent[0]==='file.pdf'));assert.throws(()=>new RealBitrixAdapter('127.0.0.1'));});
 await t.test('Installation stores encrypted tokens; login exposes app session only',async()=>{const r=await installBitrix({DOMAIN:process.env.BITRIX_PORTAL,REFRESH_ID:'initial'});assert.equal(r.user.role,'ADMIN');const tenant=await one(pool,'SELECT * FROM tenants WHERE portal=$1',[process.env.BITRIX_PORTAL]);const stored=await one(pool,'SELECT * FROM bitrix_installations WHERE tenant_id=$1',[tenant.id]);assert.equal(decrypt(stored.encryptedAccessToken),'access-1');assert.notEqual(stored.encryptedAccessToken,'access-1');const login=await bitrixLogin({DOMAIN:process.env.BITRIX_PORTAL,AUTH_ID:'access-1'});assert.ok(login.token&&!JSON.stringify(login).includes('access-1'));await assert.rejects(()=>bitrixLogin({DOMAIN:'other.bitrix24.com',AUTH_ID:'access-1'}));});
 await t.test('Expired token rotates once, persists pair, rejects mismatched portal',async()=>{expired=true;const tenant=await one(pool,'SELECT * FROM tenants WHERE portal=$1',[process.env.BITRIX_PORTAL]);const r=new RealBitrixAdapter();await r.installedCall(tenant.id,'user.current');const stored=await one(pool,'SELECT * FROM bitrix_installations WHERE tenant_id=$1',[tenant.id]);assert.equal(decrypt(stored.encryptedRefreshToken),'refresh-2');await r.installedCall(tenant.id,'user.current');assert.equal(refreshes,2);const n=calls.length;await assert.rejects(()=>new RealBitrixAdapter('other.bitrix24.com').installedCall(tenant.id,'user.current'));assert.equal(calls.length,n);});
 const webhookPayload={auth:{domain:'webhook.bitrix24.com',member_id:'webhook-member-id',access_token:'wh-access-token',refresh_token:'wh-refresh-token',application_token:'wh-application-token',expires_in:3600}};
 await t.test('ONAPPINSTALL webhook fail-closed by default: no env flag, nothing written',async()=>{delete process.env.BITRIX_INSTALL_WEBHOOK_ENABLED;const res=await onAppInstallWebhook(webhookPayload);assert.equal(res.result,false);const tenant=await one(pool,'SELECT * FROM tenants WHERE member_id=$1',['webhook-member-id']);assert.equal(tenant,undefined);});
 await t.test('ONAPPINSTALL webhook enabled: valid payload stores encrypted application_token',async()=>{process.env.BITRIX_INSTALL_WEBHOOK_ENABLED='true';const res=await onAppInstallWebhook(webhookPayload);assert.equal(res.result,true);const tenant=await one(pool,'SELECT * FROM tenants WHERE member_id=$1',['webhook-member-id']);assert.equal(tenant.portal,'webhook.bitrix24.com');const stored=await one(pool,'SELECT * FROM bitrix_installations WHERE tenant_id=$1',[tenant.id]);assert.equal(decrypt(stored.encryptedApplicationToken),'wh-application-token');assert.notEqual(stored.encryptedApplicationToken,'wh-application-token');});
 await t.test('ONAPPINSTALL webhook rejects malformed/missing fields even when enabled',async()=>{process.env.BITRIX_INSTALL_WEBHOOK_ENABLED='true';assert.equal((await onAppInstallWebhook({auth:{...webhookPayload.auth,application_token:undefined}})).result,false);assert.equal((await onAppInstallWebhook({auth:{...webhookPayload.auth,domain:'not a hostname'}})).result,false);assert.equal((await onAppInstallWebhook({auth:{...webhookPayload.auth,access_token:'short'}})).result,false);assert.equal((await onAppInstallWebhook({auth:{...webhookPayload.auth,expires_in:-1}})).result,false);});
 await t.test('verifyApplicationToken accepts only the exact stored token for that member_id',async()=>{assert.equal(await verifyApplicationToken('webhook-member-id','wh-application-token'),true);assert.equal(await verifyApplicationToken('webhook-member-id','wrong-token'),false);assert.equal(await verifyApplicationToken('unknown-member-id','wh-application-token'),false);assert.equal(await verifyApplicationToken(undefined,'wh-application-token'),false);});
 }finally{globalThis.fetch=originalFetch;await pool.end();}
});
