import { test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { randomUUID } from 'node:crypto';
test('HTTP E2E: object → 20t/10t → SK issue → acceptance → PTO → SDO → closing → dashboard/audit; tenant, RBAC, concurrency', async () => {
    if (!process.env.E2E_DATABASE_URL) delete process.env.DATABASE_URL;
    process.env.AUTH_MODE = 'mock';
    process.env.MOCK_LOGIN_KEY = 'e2e-local-test';
    process.env.DB_MODE = process.env.E2E_DATABASE_URL ? 'postgres' : 'pglite';
    process.env.PGLITE_DIR = 'memory://';
    if (process.env.E2E_DATABASE_URL) {
        if (!new URL(process.env.E2E_DATABASE_URL).pathname.endsWith('_test'))
            throw Error('E2E database name must end with _test');
        process.env.DATABASE_URL = process.env.E2E_DATABASE_URL;
    }
    const { pool, transaction, insert, one } = await import('../apps/backend/src/db');
    const { seed } = await import('../scripts/seed');
    const { createApp } = await import('../apps/backend/src/main');
    const { migrate } = await import('../scripts/migrate');
    await migrate();
    await migrate();
    await seed();
    await seed();
    const app = await createApp();
    await app.listen(0, '127.0.0.1');
    const address = app.getHttpServer().address();
    const base = `http://127.0.0.1:${address.port}`;
    let token = '';
    async function req(path: string, body?: any, expected = body === undefined ? 200 : 201) { const r = await fetch(base + '/' + path, { method: body === undefined ? 'GET' : 'POST', headers: { 'Content-Type': 'application/json', Authorization: 'Bearer ' + token }, body: body === undefined ? undefined : JSON.stringify(body) }); const data: any = await r.json(); assert.equal(r.status, expected, path + ': ' + JSON.stringify(data)); return data; }
    async function login(role: string) { const d = await req('auth/mock', { role, key: 'e2e-local-test' }); token = d.token; return d.user; }
    try {
        await req('dashboard/executive', undefined, 401);
        const pm = await login('PROJECT_MANAGER');
        const contractors = await req('contractors'), dict = await req('dictionaries');
        const c = contractors[0];
        const dt = (delta: number) => new Date(Date.now() + delta * 86400000).toISOString().slice(0, 10);
        const o = await req('objects', { externalCode: 'E2E-' + randomUUID(), name: 'E2E фундамент', address: 'Тестовый город, ул. Проверочная, 1', organizationName: 'ООО Тест', projectManagerId: pm.id, startDate: dt(-20), plannedFinishDate: dt(10), contractValue: '2000000', contractorIds: [c.id] });
        const body = { objectId: o.id, workTypeId: dict.workTypes[0].id, contractorId: c.id, responsibleUserId: pm.id, name: 'Армирование фундамента', unit: 'т', plannedQuantity: 20, plannedStartDate: dt(-20), plannedFinishDate: dt(5), estimatedCost: '1000000' };
        let w = await req('works', body), next = await req('works', { ...body, name: 'Бетонирование', unit: 'м³', plannedQuantity: 100, plannedStartDate: dt(6), plannedFinishDate: dt(10) });
        await req('work-dependencies', { predecessorWorkId: w.id, successorWorkId: next.id, requiresAcceptance: true });
        let half = await req(`works/${w.id}/progress`, { totalQuantity: 10, version: w.version, comment: 'Выполнено 10 т' });
        assert.equal(half.progressPercent, 50);
        assert.equal(half.scheduleStatus, 'RED');
        await req(`works/${w.id}/progress`, { totalQuantity: 11, version: w.version, comment: 'Устаревшая версия' }, 409);
        w = await req(`works/${w.id}/progress`, { totalQuantity: 20, version: half.version, comment: 'Армирование завершено' });
        assert.equal(w.progressPercent, 100);
        let inspection = await req(`works/${w.id}/inspection-request`, { version: w.version });
        await req(`inspections/${inspection.id}/accept`, { version: inspection.version, comment: 'Попытка РП' }, 403);
        await login('CONSTRUCTION_CONTROL');
        let issue = await req(`inspections/${inspection.id}/issues`, { version: inspection.version, title: 'Защитный слой', severity: 'CRITICAL', responsibleUserId: pm.id, dueDate: dt(1) });
        await login('PROJECT_MANAGER');
        assert.equal((await req(`works/${next.id}/transition`)).allowed, false);
        await req(`works/${next.id}/start`, { version: next.version }, 400);
        issue = await req(`issues/${issue.id}/resolve`, { version: issue.version });
        assert.equal((await req(`works/${next.id}/transition`)).allowed, false);
        await login('CONSTRUCTION_CONTROL');
        await req(`issues/${issue.id}/verify`, { version: issue.version });
        inspection = (await req('inspections')).find(x => x.id === inspection.id);
        await req(`inspections/${inspection.id}/accept`, { version: inspection.version, comment: 'Без фото' }, 400);
        const photo = await req('attachments', { fileName: 'inspection.png', mimeType: 'image/png', base64: 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aF9sAAAAASUVORK5CYII=' });
        const uploadedPhoto = await req(`inspections/${inspection.id}/photos`, { attachmentId: photo.id });
        const snapAfterPhoto = await req('snapshot');
        assert.ok(snapAfterPhoto.photos.some((p: any) => p.id === uploadedPhoto.id && p.inspectionId === inspection.id && p.attachmentId === photo.id));
        await req(`inspections/${inspection.id}/accept`, { version: inspection.version, comment: 'Повторная проверка: отклонений нет' });
        await req(`inspections/${inspection.id}/accept`, { version: inspection.version, comment: 'Повтор сетевого запроса' }, 409);
        assert.equal(Number((await pool.query("SELECT count(*) FROM audit_logs WHERE entity_id=$1 AND action='ACCEPT'", [inspection.id])).rows[0].count), 1);
        await login('PROJECT_MANAGER');
        assert.equal((await req(`works/${next.id}/transition`)).allowed, true);
        await req(`works/${next.id}/start`, { version: next.version });
        await login('PTO');
        let p = await req('executive-packages', { objectWorkId: w.id });
        assert.equal((await req(`executive-packages/${p.id}/validation`)).allowed, false);
        const file = await req('attachments', { fileName: 'passport.pdf', mimeType: 'application/pdf', base64: Buffer.from('%PDF-1.4\n% Test certificate\n%%EOF').toString('base64') });
        await req('materials/bind', { objectWorkId: w.id, name: 'Арматура А500С', manufacturer: 'Тестовый завод', batchNumber: 'П-001', quantity: 20, documentNumber: 'ПС-01', fileId: file.id, validUntil: dt(365) });
        const doc = await req('executive-documents', { packageId: p.id, type: 'AOSR', number: 'АОСР-1', documentDate: dt(0), fileId: file.id });
        assert.equal(doc.status, 'DRAFT');
        await req(`executive-documents/${doc.id}/approve`, { version: doc.version });
        p = (await req('executive-packages')).find(x => x.id === p.id);
        p = await req(`executive-packages/${p.id}/ready`, { version: p.version });
        let sdo = await req(`executive-packages/${p.id}/transfer-sdo`, { version: p.version });
        await req(`executive-packages/${p.id}/transfer-sdo`, { version: p.version }, 409);
        assert.equal(Number((await pool.query('SELECT count(*) FROM pto_transfers WHERE package_id=$1', [p.id])).rows[0].count), 1);
        await login('SDO');
        sdo = await req(`sdo/${sdo.id}/calculate`, { version: sdo.version, calculatedValue: '1000000' });
        const before = await req('dashboard/executive');
        assert.ok(before.grayObjects > 0);
        assert.ok(before.yellowObjects > 0);
        assert.ok(before.greenObjects > 0);
        assert.ok(before.redObjects > 0);
        const close = { sdoCaseId: sdo.id, amount: '1000000', period: dt(0).slice(0, 7), closingDate: dt(0), version: sdo.version, idempotencyKey: randomUUID() };
        await req('financial-closings', { ...close, amount: '1000001' }, 400);
        const f = await req('financial-closings', close);
        assert.equal((await req('financial-closings', close)).id, f.id);
        const after = await req('dashboard/executive');
        assert.equal(Number(after.closedThisMonth) - Number(before.closedThisMonth), 1000000);
        assert.equal(Number(before.potentialClosing) - Number(after.potentialClosing), 1000000);
        await login('GENERAL_DIRECTOR');
        const audit = await req('audit');
        for (const action of ['PROGRESS', 'REQUEST', 'CREATE', 'RESOLVE', 'VERIFY', 'ACCEPT', 'TRANSFER_SDO', 'CALCULATE'])
            assert.ok(audit.some(x => x.action === action), action);
        assert.equal((await req(`works/${w.id}/progress`)).length, 2);
        await login('CONTRACTOR_VIEWER');
        await req('dashboard/executive', undefined, 403);
        await req('financial-closings', close, 403);
        const snapshot = await req('snapshot');
        assert.ok(snapshot.objects.every(x => x.contractValue === undefined));
        const other = await one(pool, "INSERT INTO tenants(portal,member_id,name) VALUES('other.local','other','Other') RETURNING *");
        await assert.rejects(() => insert(pool, 'works', other.id, { ...body }), /foreign key/);
        const pm2 = await one(pool, "SELECT * FROM users WHERE tenant_id=$1 AND role='PROJECT_MANAGER' AND id<>$2 LIMIT 1", [pm.tenantId, pm.id]);
        const { session } = await import('../apps/backend/src/security');
        token = (await session(pm2)).token;
        await req(`objects/${o.id}`, undefined, 403);
        await assert.rejects(() => pool.query('UPDATE audit_logs SET action=$1 WHERE tenant_id=$2', ['TAMPER', pm.tenantId]), /Append-only/);
        await login('ADMIN');
        const ExcelJS = (await import('exceljs')).default;
        const book = new ExcelJS.Workbook();
        const sheet = book.addWorksheet('ГПО');
        sheet.addRow(['УКО', 'Объект', 'Полный адрес объекта', 'Стоимость объекта']);
        sheet.addRow(['IMPORT-E2E', 'Импортированная школа', 'ул. Тестовая, 3', 2]);
        const importedPreview = await req('imports/preview', { fileName: 'test.xlsx', base64: Buffer.from(await book.xlsx.writeBuffer()).toString('base64'), multiplier: 1000000 });
        assert.equal(importedPreview.report.rows.length, 1);
        const commit = { sourceRows: ['ГПО:2'], projectManagerId: pm.id, contractorId: c.id, startDate: dt(0), plannedFinishDate: dt(30), period: dt(0).slice(0, 7) };
        const imported = await req(`imports/${importedPreview.id}/commit`, commit);
        assert.equal(imported.imported.length, 1);
        await req(`imports/${importedPreview.id}/commit`, commit, 400);
        const { scanRisks } = await import('../apps/backend/src/risk-worker');
        await scanRisks();
        const notices = (await pool.query('SELECT count(*) FROM notifications')).rows[0].count;
        await scanRisks();
        assert.equal((await pool.query('SELECT count(*) FROM notifications')).rows[0].count, notices);
        console.log('E2E VERIFIED: 26-step workflow, RBAC, tenant FK isolation, optimistic concurrency, immutable audit, closing idempotency');
    }
    finally {
        await app.close();
        await pool.end();
    }
});
