import { Injectable, BadRequestException, ForbiddenException, NotFoundException, ConflictException } from '@nestjs/common';
import Decimal from 'decimal.js';
import { pool, one, rows, insert, transaction } from './db';
import { Actor, requirePermission, checkVersion, scoped, objectAccess, audit, ensure } from './security';
import { Permission as P, ProgressCalculationService, ScheduleStatusService, WorkTransitionPolicy, PtoPackageValidationService, PotentialClosingService, ObjectHealthService, defaultRisk, AosrDraftEngine } from '../../../packages/domain';
@Injectable()
export class ProductionService {
    async createObject(a: Actor, d: any) { requirePermission(a, P.OBJECT_CREATE); return transaction(async (c) => { ensure(d.plannedFinishDate >= d.startDate, 'Дата окончания раньше начала'); const pm = await scoped(c, 'users', d.projectManagerId, a); ensure(pm.role === 'PROJECT_MANAGER' && pm.isActive, 'Назначьте активного РП'); if (a.role === 'PROJECT_MANAGER')
        ensure(pm.id === a.id, 'РП может создать объект только для себя'); for (const id of d.contractorIds)
        await scoped(c, 'contractors', id, a); const { contractorIds, ...data } = d; const o = await insert(c, 'objects', a.tenantId, data); for (const contractorId of contractorIds)
        await insert(c, 'object_contractors', a.tenantId, { objectId: o.id, contractorId }); await audit(c, a, 'Object', o.id, 'CREATE', null, o); return o; }); }
    async assignContractor(a: Actor, objectId: string, contractorId: string) { requirePermission(a, P.OBJECT_MANAGE_CONTRACTORS); return transaction(async (c) => { await objectAccess(c, a, objectId, true); await scoped(c, 'contractors', contractorId, a); if (await one(c, 'SELECT id FROM object_contractors_active WHERE tenant_id=$1 AND object_id=$2 AND contractor_id=$3', [a.tenantId, objectId, contractorId]))
        throw new ConflictException('Подрядчик уже назначен на объект'); const row = await insert(c, 'object_contractors', a.tenantId, { objectId, contractorId }); await audit(c, a, 'ObjectContractor', row.id, 'ASSIGN', null, row); return row; }); }
    async removeContractor(a: Actor, objectId: string, contractorId: string, relationId: string, v: number) { requirePermission(a, P.OBJECT_MANAGE_CONTRACTORS); return transaction(async (c) => { await objectAccess(c, a, objectId, true); const row = await one(c, 'SELECT * FROM object_contractors_active WHERE tenant_id=$1 AND object_id=$2 AND contractor_id=$3 AND id=$4 FOR UPDATE', [a.tenantId, objectId, contractorId, relationId]); if (!row)
        throw new NotFoundException('Активное назначение подрядчика не найдено'); checkVersion(row, v); if (await one(c, "SELECT id FROM works WHERE tenant_id=$1 AND object_id=$2 AND contractor_id=$3 AND status IN ('PLANNED','ACTIVE')", [a.tenantId, objectId, contractorId]))
        throw new ConflictException('Нельзя снять подрядчика: на объекте есть его незавершённые работы'); const n = await one(c, 'UPDATE object_contractors SET removed_at=now(),removed_by=$3,version=version+1 WHERE tenant_id=$1 AND id=$2 AND removed_at IS NULL RETURNING *', [a.tenantId, relationId, a.id]); await audit(c, a, 'ObjectContractor', row.id, 'REMOVE', row, n); return n; }); }
    async editObject(a: Actor, id: string, d: any) { requirePermission(a, P.OBJECT_EDIT); return transaction(async (c) => { const o = await scoped(c, 'objects', id, a, true); await objectAccess(c, a, id, true); checkVersion(o, d.version); if ('projectManagerId' in d) {
        if (!['TECHNICAL_DIRECTOR', 'ADMIN'].includes(a.role))
            throw new ForbiddenException('Только технический директор или администратор может переназначить РП');
        if (d.projectManagerId !== o.projectManagerId) {
            const pm = await scoped(c, 'users', d.projectManagerId, a);
            ensure(pm.role === 'PROJECT_MANAGER' && pm.isActive, 'Назначьте активного РП');
        }
    } const name = d.name ?? o.name, address = d.address ?? o.address, customerName = 'customerName' in d ? d.customerName : o.customerName, plannedFinishDate = d.plannedFinishDate ?? o.plannedFinishDate, projectManagerId = d.projectManagerId ?? o.projectManagerId; ensure(plannedFinishDate >= o.startDate, 'Дата окончания раньше начала'); const n = await one(c, 'UPDATE objects SET name=$3,address=$4,customer_name=$5,planned_finish_date=$6,project_manager_id=$7,version=version+1,updated_at=now() WHERE tenant_id=$1 AND id=$2 RETURNING *', [a.tenantId, id, name, address, customerName ?? null, plannedFinishDate, projectManagerId]); await audit(c, a, 'Object', id, 'EDIT', o, n); return n; }); }
    async createWork(a: Actor, d: any) { requirePermission(a, P.WORK_CREATE); return transaction(async (c) => { await objectAccess(c, a, d.objectId, true); await scoped(c, 'work_types', d.workTypeId, a); await scoped(c, 'users', d.responsibleUserId, a); ensure(!!await one(c, 'SELECT id FROM object_contractors_active WHERE tenant_id=$1 AND object_id=$2 AND contractor_id=$3 FOR UPDATE', [a.tenantId, d.objectId, d.contractorId]), 'Субподрядчик не назначен на объект'); ensure(d.plannedFinishDate >= d.plannedStartDate, 'Некорректные сроки'); const work = await insert(c, 'works', a.tenantId, d); await audit(c, a, 'Work', work.id, 'CREATE', null, work); return work; }); }
    async transition(c: any, a: Actor, id: string) { const work = await scoped(c, 'works', id, a); await objectAccess(c, a, work.objectId); ensure(a.role !== 'CONTRACTOR_VIEWER' || a.contractorId === work.contractorId, 'Работа другого подрядчика'); const dependencies = await rows(c, `SELECT w.*, d.requires_acceptance,d.requires_document, EXISTS(SELECT 1 FROM inspections i WHERE i.tenant_id=w.tenant_id AND i.object_work_id=w.id AND i.status='ACCEPTED') AS accepted,EXISTS(SELECT 1 FROM issues x JOIN inspections i ON i.id=x.inspection_id AND i.tenant_id=x.tenant_id WHERE i.tenant_id=w.tenant_id AND i.object_work_id=w.id AND x.severity='CRITICAL' AND x.status<>'CLOSED') AS critical_issue,EXISTS(SELECT 1 FROM executive_documents e WHERE e.tenant_id=w.tenant_id AND e.object_work_id=w.id AND e.status='APPROVED') AS document_approved FROM work_dependencies d JOIN works w ON w.id=d.predecessor_work_id AND w.tenant_id=d.tenant_id WHERE d.tenant_id=$1 AND d.successor_work_id=$2`, [a.tenantId, id]); return new WorkTransitionPolicy().canStartWork(dependencies.map(p => ({ name: p.name, complete: new Decimal(p.actualQuantity).gte(p.plannedQuantity), requiresAcceptance: p.requiresAcceptance, accepted: p.accepted, criticalIssue: p.criticalIssue, documentRequired: p.requiresDocument, documentApproved: p.documentApproved }))); }
    async dependency(a: Actor, d: any) { requirePermission(a, P.WORK_CREATE); return transaction(async (c) => { const before = await scoped(c, 'works', d.predecessorWorkId, a), after = await scoped(c, 'works', d.successorWorkId, a); await objectAccess(c, a, after.objectId, true); ensure(before.objectId === after.objectId, 'Работы должны относиться к одному объекту'); await c.query('SELECT id FROM objects WHERE id=$1 FOR UPDATE', [after.objectId]); ensure(Number(after.actualQuantity) === 0 && after.status === 'PLANNED', 'Нельзя добавлять зависимость к начатой работе'); const cycle = await one(c, 'WITH RECURSIVE chain AS (SELECT successor_work_id FROM work_dependencies WHERE tenant_id=$1 AND predecessor_work_id=$2 UNION SELECT d.successor_work_id FROM work_dependencies d JOIN chain x ON d.predecessor_work_id=x.successor_work_id WHERE d.tenant_id=$1) SELECT 1 FROM chain WHERE successor_work_id=$3', [a.tenantId, d.successorWorkId, d.predecessorWorkId]); ensure(!cycle && before.id !== after.id, 'Циклическая зависимость'); const dep = await insert(c, 'work_dependencies', a.tenantId, d); await audit(c, a, 'Work', after.id, 'DEPENDENCY', null, dep); return dep; }); }
    async start(a: Actor, id: string, v: number) { requirePermission(a, P.WORK_UPDATE_PROGRESS); return transaction(async (c) => { const w = await scoped(c, 'works', id, a, true); checkVersion(w, v); const policy = await this.transition(c, a, id); ensure(policy.allowed, policy.reasons.join('; ')); ensure(w.status === 'PLANNED', 'Работа уже начата'); const n = await one(c, "UPDATE works SET status='ACTIVE',actual_start_date=CURRENT_DATE,version=version+1,updated_at=now() WHERE tenant_id=$1 AND id=$2 RETURNING *", [a.tenantId, id]); await audit(c, a, 'Work', id, 'START', w, n); return n; }); }
    async progress(a: Actor, id: string, d: any) { requirePermission(a, P.WORK_UPDATE_PROGRESS); return transaction(async (c) => { const w = await scoped(c, 'works', id, a, true); await objectAccess(c, a, w.objectId, true); checkVersion(w, d.version); const allowed = await this.transition(c, a, id); ensure(allowed.allowed, allowed.reasons.join('; ')); ensure(!await one(c, "SELECT id FROM inspections WHERE tenant_id=$1 AND object_work_id=$2 AND status NOT IN ('REJECTED','NOT_SUBMITTED')", [a.tenantId, id]), 'После предъявления СК факт заблокирован. Требуется отдельная корректировка'); const percent = new ProgressCalculationService().calculate(d.totalQuantity, w.plannedQuantity); const n = await one(c, "UPDATE works SET actual_quantity=$3,status=$4,actual_start_date=coalesce(actual_start_date,CURRENT_DATE),actual_finish_date=CASE WHEN $4='COMPLETED' THEN CURRENT_DATE ELSE NULL END,version=version+1,updated_at=now() WHERE tenant_id=$1 AND id=$2 RETURNING *", [a.tenantId, id, d.totalQuantity, percent === 100 ? 'COMPLETED' : 'ACTIVE']); await insert(c, 'work_progress', a.tenantId, { objectWorkId: id, quantityDelta: new Decimal(d.totalQuantity).minus(w.actualQuantity).toString(), totalQuantity: d.totalQuantity, progressPercent: percent, reportedBy: a.id, comment: d.comment }); await audit(c, a, 'Work', id, 'PROGRESS', w, n, 'WorkProgressUpdated'); return { ...n, progressPercent: percent, isOverperformed: new ProgressCalculationService().isOverperformed(d.totalQuantity, w.plannedQuantity), ...new ScheduleStatusService().calculate(n.plannedStartDate, n.plannedFinishDate, percent) }; }); }
    async requestInspection(a: Actor, id: string, v: number) { requirePermission(a, P.INSPECTION_REQUEST); return transaction(async (c) => { const w = await scoped(c, 'works', id, a, true); await objectAccess(c, a, w.objectId, true); checkVersion(w, v); ensure(new Decimal(w.actualQuantity).gte(w.plannedQuantity), 'Для MVP предъявляется полный объём работы'); ensure(!await one(c, "SELECT id FROM inspections WHERE tenant_id=$1 AND object_work_id=$2 AND status='ACCEPTED'", [a.tenantId, id]), 'Работа уже принята'); const i = await insert(c, 'inspections', a.tenantId, { objectId: w.objectId, objectWorkId: id, requestedBy: a.id }); await c.query('UPDATE works SET version=version+1 WHERE tenant_id=$1 AND id=$2', [a.tenantId, id]); await audit(c, a, 'Inspection', i.id, 'REQUEST', null, i, 'InspectionRequested'); return i; }); }
    async addIssue(a: Actor, id: string, d: any) { requirePermission(a, P.ISSUE_CREATE); return transaction(async (c) => { const i = await scoped(c, 'inspections', id, a, true); await objectAccess(c, a, i.objectId); checkVersion(i, d.version); ensure(['WAITING', 'IN_REVIEW', 'REINSPECTION', 'ISSUES_FOUND'].includes(i.status), 'Проверка завершена'); await scoped(c, 'users', d.responsibleUserId, a); const { version, ...data } = d; const issue = await insert(c, 'issues', a.tenantId, { inspectionId: id, ...data }); await c.query("UPDATE inspections SET status='ISSUES_FOUND',inspector_id=$3,version=version+1 WHERE tenant_id=$1 AND id=$2", [a.tenantId, id, a.id]); await audit(c, a, 'Issue', issue.id, 'CREATE', null, issue, 'IssueCreated'); return issue; }); }
    async issueAction(a: Actor, id: string, v: number, action: string) { requirePermission(a, action === 'resolve' ? P.ISSUE_RESOLVE : P.ISSUE_VERIFY); return transaction(async (c) => { const first = await scoped(c, 'issues', id, a); const i = await scoped(c, 'inspections', first.inspectionId, a, true); const issue = await scoped(c, 'issues', id, a, true); await objectAccess(c, a, i.objectId, true); checkVersion(issue, v); if (action === 'resolve')
        ensure(['OPEN', 'IN_PROGRESS', 'REJECTED'].includes(issue.status), 'Замечание не ожидает устранения');
    else
        ensure(issue.status === 'READY_FOR_VERIFICATION', 'Сначала РП должен устранить замечание'); const n = action === 'resolve' ? await one(c, "UPDATE issues SET status='READY_FOR_VERIFICATION',resolved_at=now(),resolved_by=$3,version=version+1 WHERE tenant_id=$1 AND id=$2 RETURNING *", [a.tenantId, id, a.id]) : await one(c, "UPDATE issues SET status='CLOSED',verified_at=now(),verified_by=$3,version=version+1 WHERE tenant_id=$1 AND id=$2 RETURNING *", [a.tenantId, id, a.id]); await c.query("UPDATE inspections SET status='REINSPECTION',version=version+1 WHERE tenant_id=$1 AND id=$2", [a.tenantId, i.id]); await audit(c, a, 'Issue', id, action.toUpperCase(), issue, n, action === 'resolve' ? 'IssueResolved' : undefined); return n; }); }
    async inspectionAction(a: Actor, id: string, v: number, action: string, comment: string) { requirePermission(a, action === 'accept' ? P.INSPECTION_ACCEPT : P.INSPECTION_REJECT); return transaction(async (c) => { const i = await scoped(c, 'inspections', id, a, true); await objectAccess(c, a, i.objectId); checkVersion(i, v); ensure(['WAITING', 'IN_REVIEW', 'ISSUES_FOUND', 'REINSPECTION'].includes(i.status), 'Проверка уже завершена'); if (action === 'accept') {
        ensure(!await one(c, "SELECT id FROM issues WHERE tenant_id=$1 AND inspection_id=$2 AND status<>'CLOSED'", [a.tenantId, id]), 'Не все замечания проверены и закрыты');
        ensure(!!await one(c, 'SELECT id FROM inspection_photos WHERE tenant_id=$1 AND inspection_id=$2', [a.tenantId, id]), 'Необходима фотофиксация проверки');
    } const n = await one(c, "UPDATE inspections SET status=$3,decision=$3,comment=$4,inspector_id=$5,inspection_date=now(),accepted_at=CASE WHEN $3='ACCEPTED' THEN now() ELSE NULL END,version=version+1 WHERE tenant_id=$1 AND id=$2 RETURNING *", [a.tenantId, id, action === 'accept' ? 'ACCEPTED' : 'REJECTED', comment, a.id]); await c.query('UPDATE works SET version=version+1,updated_at=now() WHERE tenant_id=$1 AND id=$2', [a.tenantId, i.objectWorkId]); await audit(c, a, 'Inspection', id, action.toUpperCase(), i, n, action === 'accept' ? 'InspectionAccepted' : 'InspectionRejected'); return n; }); }
    async createPackage(a: Actor, workId: string) { requirePermission(a, P.PTO_EDIT); return transaction(async (c) => { const w = await scoped(c, 'works', workId, a); await objectAccess(c, a, w.objectId); const p = await insert(c, 'executive_packages', a.tenantId, { objectId: w.objectId, objectWorkId: workId, createdBy: a.id }); await audit(c, a, 'Package', p.id, 'CREATE', null, p); return p; }); }
    async createDocument(a: Actor, d: any) { requirePermission(a, P.PTO_EDIT); return transaction(async (c) => { const p = await scoped(c, 'executive_packages', d.packageId, a, true); await objectAccess(c, a, p.objectId); ensure(!['TRANSFERRED_TO_SDO'].includes(p.status), 'Пакет уже передан'); const w = await scoped(c, 'works', p.objectWorkId, a), o = await scoped(c, 'objects', p.objectId, a); if (d.fileId)
        await scoped(c, 'attachments', d.fileId, a); const draft = new AosrDraftEngine().render({ Объект: o.name, Адрес: o.address, Работа: w.name, Начало: w.actualStartDate, Окончание: w.actualFinishDate }); const doc = await insert(c, 'executive_documents', a.tenantId, { objectId: p.objectId, objectWorkId: p.objectWorkId, type: d.type, number: d.number, documentDate: d.documentDate, status: 'DRAFT', fileId: d.fileId ?? null, draftContent: draft.content, createdBy: a.id }); await insert(c, 'package_documents', a.tenantId, { packageId: p.id, documentId: doc.id }); await c.query("UPDATE executive_packages SET status='IN_PROGRESS',version=version+1 WHERE tenant_id=$1 AND id=$2", [a.tenantId, p.id]); await audit(c, a, 'Document', doc.id, 'DRAFT', null, doc); return doc; }); }
    async approveDocument(a: Actor, id: string, v: number) { requirePermission(a, P.PTO_EDIT); return transaction(async (c) => { const doc = await scoped(c, 'executive_documents', id, a, true); await objectAccess(c, a, doc.objectId); checkVersion(doc, v); ensure(doc.status !== 'APPROVED', 'Документ уже подтверждён'); ensure(!!doc.fileId, 'Прикрепите проверенный документ; текст черновика не заменяет файл'); const n = await one(c, "UPDATE executive_documents SET status='APPROVED',approved_by=$3,approved_at=now(),version=version+1 WHERE tenant_id=$1 AND id=$2 RETURNING *", [a.tenantId, id, a.id]); await audit(c, a, 'Document', id, 'APPROVE', doc, n); return n; }); }
    async packageValidation(c: any, a: Actor, id: string) { const p = await scoped(c, 'executive_packages', id, a); await objectAccess(c, a, p.objectId); const w = await one(c, 'SELECT w.*,t.requires_inspection,t.requires_materials FROM works w JOIN work_types t ON t.id=w.work_type_id AND t.tenant_id=w.tenant_id WHERE w.tenant_id=$1 AND w.id=$2', [a.tenantId, p.objectWorkId]); const docs = await rows(c, 'SELECT d.* FROM package_documents p JOIN executive_documents d ON d.id=p.document_id AND d.tenant_id=p.tenant_id WHERE p.tenant_id=$1 AND p.package_id=$2', [a.tenantId, id]); const materials = await rows(c, `SELECT wm.id,EXISTS(SELECT 1 FROM material_documents d WHERE d.tenant_id=wm.tenant_id AND d.material_batch_id=wm.material_batch_id AND d.type IN ('CERTIFICATE','PASSPORT','DECLARATION','QUALITY_DOCUMENT') AND (d.valid_from IS NULL OR d.valid_from<=CURRENT_DATE) AND (d.valid_until IS NULL OR d.valid_until>=CURRENT_DATE)) AS valid FROM work_materials wm WHERE wm.tenant_id=$1 AND wm.object_work_id=$2`, [a.tenantId, w.id]); const accepted = !!await one(c, "SELECT id FROM inspections WHERE tenant_id=$1 AND object_work_id=$2 AND status='ACCEPTED'", [a.tenantId, w.id]); return new PtoPackageValidationService().validate({ accepted, requiresInspection: w.requiresInspection, documents: docs, requiresMaterials: w.requiresMaterials, materialsValid: materials.length > 0 && materials.every(x => x.valid) }); }
    async packageAction(a: Actor, id: string, v: number, action: string) { requirePermission(a, action === 'transfer-sdo' ? P.PTO_TRANSFER_SDO : P.PTO_EDIT); return transaction(async (c) => { const p = await scoped(c, 'executive_packages', id, a, true); checkVersion(p, v); ensure(p.status !== 'TRANSFERRED_TO_SDO', 'Пакет уже передан'); const validation = await this.packageValidation(c, a, id); ensure(validation.allowed, validation.reasons.join('; ')); if (action === 'ready') {
        const n = await one(c, "UPDATE executive_packages SET status='READY',completed_at=now(),version=version+1 WHERE tenant_id=$1 AND id=$2 RETURNING *", [a.tenantId, id]);
        await audit(c, a, 'Package', id, 'READY', p, n, 'ExecutivePackageReady');
        return n;
    } ensure(p.status === 'READY', 'Сначала отметьте готовность пакета'); await insert(c, 'pto_transfers', a.tenantId, { packageId: id, transferredBy: a.id }); const w = await scoped(c, 'works', p.objectWorkId, a); ensure(!await one(c, 'SELECT id FROM sdo_cases WHERE tenant_id=$1 AND object_work_id=$2', [a.tenantId, w.id]), 'Для работы уже создано дело СДО'); const sdo = await insert(c, 'sdo_cases', a.tenantId, { objectId: p.objectId, objectWorkId: p.objectWorkId, executiveDocumentPackageId: id, ptoTransferredBy: a.id, estimatedValue: w.estimatedCost }); await c.query("UPDATE executive_packages SET status='TRANSFERRED_TO_SDO',version=version+1 WHERE tenant_id=$1 AND id=$2", [a.tenantId, id]); await audit(c, a, 'Package', id, 'TRANSFER_SDO', p, sdo, 'TransferredToSdo'); return sdo; }); }
    async calculateSdo(a: Actor, id: string, d: any) { requirePermission(a, P.SDO_EDIT); return transaction(async (c) => { const s = await scoped(c, 'sdo_cases', id, a, true); await objectAccess(c, a, s.objectId); checkVersion(s, d.version); ensure(['TRANSFERRED', 'IN_PROGRESS', 'NEEDS_CLARIFICATION', 'CALCULATED'].includes(s.status), 'Дело уже закрывается'); const n = await one(c, "UPDATE sdo_cases SET calculated_value=$3,accepted_closing_value=$3,status='CALCULATED',sdo_responsible_id=$4,calculated_at=now(),version=version+1 WHERE tenant_id=$1 AND id=$2 RETURNING *", [a.tenantId, id, d.calculatedValue, a.id]); await audit(c, a, 'SdoCase', id, 'CALCULATE', s, n, 'SdoCalculated'); return n; }); }
    async close(a: Actor, d: any) { requirePermission(a, P.SDO_CLOSE); requirePermission(a, P.FINANCE_EDIT); return transaction(async (c) => { const s = await scoped(c, 'sdo_cases', d.sdoCaseId, a, true); await objectAccess(c, a, s.objectId); const existing = await one(c, 'SELECT * FROM financial_closings WHERE tenant_id=$1 AND idempotency_key=$2', [a.tenantId, d.idempotencyKey]); if (existing) {
        ensure(existing.sdoCaseId === s.id && new Decimal(existing.amount).eq(d.amount) && existing.period === d.period && new Date(existing.closingDate).toISOString().slice(0, 10) === d.closingDate, 'Idempotency key уже использован с другими данными');
        return existing;
    } checkVersion(s, d.version); ensure(['CALCULATED', 'READY_TO_CLOSE'].includes(s.status), 'Стоимость ещё не рассчитана или дело закрыто'); const sum = await one(c, 'SELECT coalesce(sum(amount),0) AS amount FROM financial_closings WHERE tenant_id=$1 AND sdo_case_id=$2', [a.tenantId, s.id]); ensure(new Decimal(sum.amount).add(d.amount).lte(s.acceptedClosingValue), 'Сумма превышает доступное закрытие'); ensure(d.closingDate.slice(0, 7) === d.period, 'Период не соответствует дате закрытия'); const f = await insert(c, 'financial_closings', a.tenantId, { objectId: s.objectId, sdoCaseId: s.id, period: d.period, amount: d.amount, closingDate: d.closingDate, createdBy: a.id, idempotencyKey: d.idempotencyKey }); const all = new Decimal(sum.amount).add(d.amount).eq(s.acceptedClosingValue); await c.query("UPDATE sdo_cases SET status=$3,closed_at=CASE WHEN $3='CLOSED' THEN now() ELSE NULL END,version=version+1 WHERE tenant_id=$1 AND id=$2", [a.tenantId, s.id, all ? 'CLOSED' : 'READY_TO_CLOSE']); await audit(c, a, 'FinancialClosing', f.id, 'CREATE', null, f, 'FinancialClosingCreated'); return f; }); }
}
