/**
 * Demo data for the C01 / O01 / W01 screen previews.
 *
 * Typed against the real backend contract (`types/api.ts`), not invented shapes
 * — every field here is one the API actually returns. Values themselves are
 * invented for display, the same status this file's sibling components' demo
 * data already has in the F1–F3 gallery.
 *
 * Deliberately its own vocabulary — different object names, codes and work
 * names from the F1–F3 gallery sections above it on the same preview page —
 * rather than reusing `CC-024`/"Учебный корпус · Северный"/"Штукатурка" and
 * so on. Those already exist once on the page as F2/F3's own demonstration
 * rows, and several existing specs in `tests/design-system/` locate them by
 * page-wide (unscoped) role/text queries; a second row with the same
 * accessible name anywhere on the page would make those queries ambiguous.
 *
 * `financial`, `estimatedCost`, `closed`, `potential` and `contractValue` are
 * left out everywhere they are optional. None of C01/O01/W01 render financial
 * closing, so there was nothing to invent a plausible number for.
 */

import type { Inspection, ObjectSummary, Work } from '../../types/api';

const TENANT = 'demo-tenant';

function versioned(id: string, createdAt: string) {
  return { id, tenantId: TENANT, createdAt, updatedAt: createdAt, version: 1 };
}

export const demoObjects: ObjectSummary[] = [
  {
    ...versioned('demo-object-1', '2026-02-01T09:00:00Z'),
    externalCode: 'CC-052',
    source: 'MANUAL',
    name: 'Жилой комплекс «Полесье»',
    address: 'ул. Лесная, 8',
    customerName: 'ООО «Полесье Девелопмент»',
    organizationName: 'ООО СЗ «Гор-Строй»',
    projectManagerId: 'demo-user-pm-1',
    startDate: '2026-02-01',
    plannedFinishDate: '2026-12-15',
    actualFinishDate: null,
    status: 'ACTIVE',
    healthStatus: 'RED',
    responsible: 'Дмитрий Соколов',
    contractorIds: ['demo-contractor-1'],
    contractors: ['ООО «ФасадСтройГрупп»'],
    actualProgress: 62,
    plannedProgress: 75,
  },
  {
    ...versioned('demo-object-2', '2026-01-12T09:00:00Z'),
    externalCode: 'CC-047',
    source: 'MANUAL',
    name: 'Бизнес-центр «Горизонт»',
    address: 'пр. Ленина, 55',
    customerName: null,
    organizationName: 'ООО СЗ «Гор-Строй»',
    projectManagerId: 'demo-user-pm-2',
    startDate: '2026-01-15',
    plannedFinishDate: '2026-11-30',
    actualFinishDate: null,
    status: 'ACTIVE',
    healthStatus: 'GREEN',
    responsible: 'Мария Петрова',
    contractorIds: ['demo-contractor-2'],
    contractors: ['ООО «СтройМонтажСервис»'],
    actualProgress: 88,
    plannedProgress: 85,
  },
  {
    ...versioned('demo-object-3', '2026-08-01T09:00:00Z'),
    externalCode: 'CC-039',
    source: 'MANUAL',
    name: 'Логистический терминал',
    address: 'трасса М-7, 14 км',
    customerName: 'ООО «Карго Лоджистикс»',
    organizationName: 'ООО СЗ «Гор-Строй»',
    projectManagerId: 'demo-user-pm-3',
    startDate: '2026-09-01',
    plannedFinishDate: '2027-04-30',
    actualFinishDate: null,
    status: 'PLANNED',
    healthStatus: 'GRAY',
    responsible: 'Олег Никитин',
    contractorIds: [],
    contractors: [],
    actualProgress: null,
    plannedProgress: null,
  },
  {
    // A fourth object exists specifically so the attention queue has a case of
    // its own: a schedule delay with no blocker anywhere on the object, distinct
    // from object 1's blocker (which, being the more severe signal, is what the
    // queue reports for object 1 — see `buildC01ViewModel`'s `ATTENTION_RANK`).
    ...versioned('demo-object-4', '2026-05-01T09:00:00Z'),
    externalCode: 'CC-061',
    source: 'MANUAL',
    name: 'Складской комплекс «Восток»',
    address: 'ул. Портовая, 21',
    customerName: 'ООО «Восток Логистик»',
    organizationName: 'ООО СЗ «Гор-Строй»',
    projectManagerId: 'demo-user-pm-3',
    startDate: '2026-05-01',
    plannedFinishDate: '2026-10-31',
    actualFinishDate: null,
    status: 'ACTIVE',
    healthStatus: 'RED',
    responsible: 'Олег Никитин',
    contractorIds: ['demo-contractor-4'],
    contractors: ['ООО «ГидроСтройМонтаж»'],
    actualProgress: 45,
    plannedProgress: 70,
  },
];

export const demoWorks: Work[] = [
  // Object 1 — Жилой комплекс «Полесье»: one delayed work (the Plan/Fact/СК
  // confirmation showcase for W01 — see fixtures below), one completed and
  // confirmed, one blocked, one with no report yet.
  {
    ...versioned('demo-work-1-1', '2026-06-01T09:00:00Z'),
    objectId: 'demo-object-1',
    workTypeId: 'demo-work-type-facade-finish',
    contractorId: 'demo-contractor-1',
    responsibleUserId: 'demo-user-pm-1',
    name: 'Отделка фасада',
    unit: 'м²',
    plannedQuantity: '1000.0000',
    actualQuantity: '500.0000',
    plannedStartDate: '2026-06-01',
    plannedFinishDate: '2026-08-15',
    actualStartDate: '2026-06-03',
    actualFinishDate: null,
    status: 'ACTIVE',
    categoryId: 'demo-category-finishing',
    requiresInspection: true,
    requiresMaterials: true,
    contractor: 'ООО «ФасадСтройГрупп»',
    responsible: 'Дмитрий Соколов',
    lastReportedAt: '2026-09-20T10:00:00Z',
    plannedProgress: 80,
    actualProgress: 50,
    variance: -30,
    delayDays: 18,
    scheduleStatus: 'RED',
    accepted: false,
    docsReady: false,
    blockers: [],
    stale: false,
  },
  {
    ...versioned('demo-work-1-2', '2026-02-10T09:00:00Z'),
    objectId: 'demo-object-1',
    workTypeId: 'demo-work-type-facade-insulation',
    contractorId: 'demo-contractor-1',
    responsibleUserId: 'demo-user-pm-1',
    name: 'Утепление фасада',
    unit: 'м²',
    plannedQuantity: '800.0000',
    actualQuantity: '800.0000',
    plannedStartDate: '2026-02-15',
    plannedFinishDate: '2026-04-01',
    actualStartDate: '2026-02-15',
    actualFinishDate: '2026-03-28',
    status: 'COMPLETED',
    categoryId: 'demo-category-finishing',
    requiresInspection: true,
    requiresMaterials: true,
    contractor: 'ООО «ФасадСтройГрупп»',
    responsible: 'Дмитрий Соколов',
    lastReportedAt: '2026-03-28T15:00:00Z',
    plannedProgress: 100,
    actualProgress: 100,
    variance: 0,
    delayDays: 0,
    scheduleStatus: 'GREEN',
    accepted: true,
    docsReady: true,
    blockers: [],
    stale: false,
  },
  {
    ...versioned('demo-work-1-3', '2026-08-01T09:00:00Z'),
    objectId: 'demo-object-1',
    workTypeId: 'demo-work-type-curtain-wall',
    contractorId: 'demo-contractor-1',
    responsibleUserId: 'demo-user-pm-1',
    name: 'Монтаж вентфасада',
    unit: 'м²',
    plannedQuantity: '1000.0000',
    actualQuantity: '0.0000',
    plannedStartDate: '2026-08-20',
    plannedFinishDate: '2026-10-01',
    actualStartDate: null,
    actualFinishDate: null,
    status: 'PLANNED',
    categoryId: 'demo-category-finishing',
    requiresInspection: true,
    requiresMaterials: true,
    contractor: 'ООО «ФасадСтройГрупп»',
    responsible: 'Дмитрий Соколов',
    lastReportedAt: null,
    plannedProgress: 15,
    actualProgress: null,
    variance: null,
    delayDays: 0,
    scheduleStatus: 'GRAY',
    accepted: false,
    docsReady: false,
    blockers: ['Отделка фасада: не завершена'],
    stale: false,
  },
  {
    ...versioned('demo-work-1-4', '2026-09-01T09:00:00Z'),
    objectId: 'demo-object-1',
    workTypeId: 'demo-work-type-glazing',
    contractorId: 'demo-contractor-1',
    responsibleUserId: 'demo-user-pm-1',
    name: 'Остекление',
    unit: 'м²',
    plannedQuantity: '1000.0000',
    actualQuantity: '0.0000',
    plannedStartDate: '2026-10-05',
    plannedFinishDate: '2026-11-01',
    actualStartDate: null,
    actualFinishDate: null,
    status: 'PLANNED',
    categoryId: 'demo-category-finishing',
    requiresInspection: true,
    requiresMaterials: false,
    contractor: 'ООО «ФасадСтройГрупп»',
    responsible: 'Дмитрий Соколов',
    lastReportedAt: null,
    plannedProgress: null,
    actualProgress: null,
    variance: null,
    delayDays: 0,
    scheduleStatus: 'GRAY',
    accepted: false,
    docsReady: false,
    blockers: [],
    stale: false,
  },

  // Object 2 — Бизнес-центр «Горизонт»: on schedule, one awaiting СК review.
  {
    ...versioned('demo-work-2-1', '2026-03-01T09:00:00Z'),
    objectId: 'demo-object-2',
    workTypeId: 'demo-work-type-frame',
    contractorId: 'demo-contractor-2',
    responsibleUserId: 'demo-user-pm-2',
    name: 'Монтаж каркаса',
    unit: 'м³',
    plannedQuantity: '500.0000',
    actualQuantity: '460.0000',
    plannedStartDate: '2026-03-01',
    plannedFinishDate: '2026-09-30',
    actualStartDate: '2026-03-02',
    actualFinishDate: null,
    status: 'ACTIVE',
    categoryId: 'demo-category-structural',
    requiresInspection: true,
    requiresMaterials: true,
    contractor: 'ООО «СтройМонтажСервис»',
    responsible: 'Мария Петрова',
    lastReportedAt: '2026-09-18T12:00:00Z',
    plannedProgress: 90,
    actualProgress: 92,
    variance: 2,
    delayDays: 0,
    scheduleStatus: 'GREEN',
    accepted: false,
    docsReady: false,
    blockers: [],
    stale: false,
  },
  {
    ...versioned('demo-work-2-2', '2026-01-20T09:00:00Z'),
    objectId: 'demo-object-2',
    workTypeId: 'demo-work-type-slabs',
    contractorId: 'demo-contractor-2',
    responsibleUserId: 'demo-user-pm-2',
    name: 'Устройство перекрытий',
    unit: 'м²',
    plannedQuantity: '300.0000',
    actualQuantity: '300.0000',
    plannedStartDate: '2026-01-20',
    plannedFinishDate: '2026-03-01',
    actualStartDate: '2026-01-20',
    actualFinishDate: '2026-02-25',
    status: 'COMPLETED',
    categoryId: 'demo-category-structural',
    requiresInspection: true,
    requiresMaterials: true,
    contractor: 'ООО «СтройМонтажСервис»',
    responsible: 'Мария Петрова',
    lastReportedAt: '2026-02-25T09:00:00Z',
    plannedProgress: 100,
    actualProgress: 100,
    variance: 0,
    delayDays: 0,
    scheduleStatus: 'GREEN',
    accepted: true,
    docsReady: true,
    blockers: [],
    stale: false,
  },

  // Object 3 — Логистический терминал: just planned, nothing reported yet.
  {
    ...versioned('demo-work-3-1', '2026-09-05T09:00:00Z'),
    objectId: 'demo-object-3',
    workTypeId: 'demo-work-type-roofing',
    contractorId: 'demo-contractor-3',
    responsibleUserId: 'demo-user-pm-3',
    name: 'Устройство кровли',
    unit: 'м²',
    plannedQuantity: '1200.0000',
    actualQuantity: '0.0000',
    plannedStartDate: '2026-09-10',
    plannedFinishDate: '2026-12-01',
    actualStartDate: null,
    actualFinishDate: null,
    status: 'PLANNED',
    categoryId: 'demo-category-roofing',
    requiresInspection: true,
    requiresMaterials: true,
    contractor: 'не назначен',
    responsible: 'Олег Никитин',
    lastReportedAt: null,
    plannedProgress: null,
    actualProgress: null,
    variance: null,
    delayDays: 0,
    scheduleStatus: 'GRAY',
    accepted: false,
    docsReady: false,
    blockers: [],
    stale: false,
  },

  // Object 4 — Складской комплекс «Восток»: behind schedule, nothing blocking it.
  {
    ...versioned('demo-work-4-1', '2026-05-01T09:00:00Z'),
    objectId: 'demo-object-4',
    workTypeId: 'demo-work-type-waterproofing',
    contractorId: 'demo-contractor-4',
    responsibleUserId: 'demo-user-pm-3',
    name: 'Гидроизоляция фундамента',
    unit: 'м²',
    plannedQuantity: '600.0000',
    actualQuantity: '270.0000',
    plannedStartDate: '2026-05-05',
    plannedFinishDate: '2026-07-01',
    actualStartDate: '2026-05-06',
    actualFinishDate: null,
    status: 'ACTIVE',
    categoryId: 'demo-category-structural',
    requiresInspection: true,
    requiresMaterials: true,
    contractor: 'ООО «ГидроСтройМонтаж»',
    responsible: 'Олег Никитин',
    lastReportedAt: '2026-09-10T09:00:00Z',
    plannedProgress: 75,
    actualProgress: 45,
    variance: -30,
    delayDays: 22,
    scheduleStatus: 'RED',
    accepted: false,
    docsReady: false,
    blockers: [],
    stale: false,
  },
];

export const demoInspections: Inspection[] = [
  {
    ...versioned('demo-inspection-2-1', '2026-09-18T13:00:00Z'),
    objectId: 'demo-object-2',
    objectWorkId: 'demo-work-2-1',
    requestedBy: 'demo-user-pm-2',
    requestedAt: '2026-09-18T13:00:00Z',
    inspectorId: null,
    status: 'WAITING',
    inspectionDate: null,
    decision: null,
    comment: null,
    acceptedAt: null,
  },
  {
    ...versioned('demo-inspection-1-2', '2026-03-29T09:00:00Z'),
    objectId: 'demo-object-1',
    objectWorkId: 'demo-work-1-2',
    requestedBy: 'demo-user-pm-1',
    requestedAt: '2026-03-29T09:00:00Z',
    inspectorId: 'demo-user-sk-1',
    status: 'ACCEPTED',
    inspectionDate: '2026-03-30T09:00:00Z',
    decision: 'Принято без замечаний',
    comment: null,
    acceptedAt: '2026-03-30T09:00:00Z',
  },
];

/** The object O01's preview renders — the richest of the three: delayed, blocked and completed work side by side. */
export const demoSelectedObjectId = 'demo-object-1';

/** The work W01's preview renders — the delayed work, so the СК confirmation demonstration sits next to a real Plan/Fact gap. */
export const demoSelectedWorkId = 'demo-work-1-1';
